#!/bin/bash
set -uo pipefail
export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"
ROOT="$(git rev-parse --show-toplevel)"||exit 1;cd "$ROOT"||exit 1
SPEC="$ROOT/e2e/specs/feeds-main-redesign.spec.cjs"; OUT="$ROOT/.agents/tester/RESULTS/feeds-main-redesign";mkdir -p "$OUT/screenshots"
BACKUP="$OUT/.spec-original-backup";cp "$SPEC" "$BACKUP";restore(){ cp "$BACKUP" "$SPEC";rm -f "$BACKUP";};trap restore EXIT INT TERM
cat > "$SPEC" <<'NODE'
const {test}=require('@playwright/test'),fs=require('fs'),path=require('path');
test('authenticated via unchanged original pack server',async({page})=>{const out=process.env.FEEDS_MAIN_ARTIFACTS,base=process.env.FEEDS_MAIN_BASE;const r=await page.goto(base+'/login');await page.screenshot({path:path.join(out,'screenshots','original-server-signin.png'),fullPage:true});const btn=page.locator('[data-testid="demo-login-btn"]');const result={loginURL:page.url(),status:r&&r.status(),buttonCount:await btn.count(),visible:await btn.isVisible().catch(()=>false)};if(!result.visible)throw Error('demo login missing '+JSON.stringify(result));const wait=page.waitForResponse(x=>x.url().includes('/api/v1/auth/demo'),{timeout:20000}).catch(()=>null);await btn.click();const auth=await wait;result.demoStatus=auth?.status()??null;result.demoBody=auth?await auth.text():null;await page.waitForURL(/\/feed(?:[?#].*)?$/,{timeout:15000}).catch(()=>{});result.finalURL=page.url();await page.waitForTimeout(600);result.families=await page.evaluate(async()=>{const r=await fetch('/api/v1/families',{credentials:'include'}),j=await r.json(),a=j.families||j;return{status:r.status,count:Array.isArray(a)?a.length:null,firstId:Array.isArray(a)&&a[0]?a[0].id:null,firstName:Array.isArray(a)&&a[0]?a[0].name:null,keys:Object.keys(j)}});const nf=page.locator('[data-testid="no-family"]');result.feed={composer:await page.locator('[data-testid="composer-form"]').count(),noFamily:await nf.isVisible().catch(()=>false),noFamilyText:await nf.innerText().catch(()=>null),anonymousHint:await page.locator('[data-testid="anonymous-hint"]').count(),posts:await page.locator('article').count()};await page.screenshot({path:path.join(out,'screenshots','original-server-feed-state.png'),fullPage:true});fs.writeFileSync(path.join(out,'original-server-final.json'),JSON.stringify(result,null,2));console.log('AUTH_GATING_EVIDENCE '+JSON.stringify(result));});
NODE
perl -e 'use strict;use warnings;use POSIX ":sys_wait_h";my $c;$SIG{ALRM}=sub{kill "INT",-$c;kill "INT",$c;sleep 2;kill "TERM",-$c;kill "TERM",$c;sleep 2;kill "KILL",-$c;kill "KILL",$c;waitpid($c,0);exit 124};$c=fork();exit 125 unless defined $c;if(!$c){setpgrp(0,0);exec @ARGV;exit 127}setpgrp(0,$c);alarm 300;waitpid($c,0);my $r=$?;alarm 0;exit((($r&127)!=0)?1:($r>>8));' bash "$ROOT/.agents/tester/packs/feeds_main_browser_test.sh.worker"
