const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const base=process.env.APPLE_PHASE1_BASE;
if(!base||!/^http:\/\/127\.0\.0\.1:1[0-9]{4}$/.test(base))throw new Error('Pack-managed local preview URL required');
const out=process.env.APPLE_PHASE1_ARTIFACTS||path.resolve(__dirname,'../../.agents/tester/RESULTS/apple_phase1_shell_e2e'),rows=[];
async function check(p,name,selector,width,theme,fn){const r={name,selector,viewport:width,theme,status:'FAIL'};try{r.measurements=await fn();r.status='PASS'}catch(e){r.error=String(e.message||e)}const screenshot=`${name}-vp${width}-${theme}.png`;try{await p.screenshot({path:path.join(out,screenshot),fullPage:true});r.screenshot=screenshot}catch(e){r.screenshotError=String(e.message||e)}rows.push(r)}
const lum=rgb=>{const c=rgb.match(/[\d.]+/g);if(!c||c.length<3)return NaN;const x=c.slice(0,3).map(v=>+v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*x[0]+.7152*x[1]+.0722*x[2]},ratio=(a,b)=>{const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
async function shell(p,w,t){
 await check(p,`shell-${w}-${t}-overflow`,'documentElement',w,t,async()=>{const x=await p.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth}));expect(x.scrollWidth).toBeLessThanOrEqual(x.clientWidth);return x});
 await check(p,`shell-${w}-${t}-aria-current`,'nav a[aria-current=page]',w,t,async()=>{const n=p.locator('nav[aria-label="Điều hướng chính"],nav[aria-label="Điều hướng di động"]:visible');await expect(n.first()).toBeVisible();const a=n.locator('a[aria-current="page"]');await expect(a).toHaveCount(1);return{label:await a.innerText(),href:await a.getAttribute('href')}});
 await check(p,`shell-${w}-${t}-focus`,':focus-visible',w,t,async()=>{await p.evaluate(()=>document.activeElement.blur());await p.keyboard.press('Tab');const e=p.locator(':focus-visible');await expect(e).toHaveCount(1);const v=await e.evaluate(x=>({tag:x.tagName,outline:getComputedStyle(x).outlineStyle,outlineWidth:getComputedStyle(x).outlineWidth,shadow:getComputedStyle(x).boxShadow}));expect(v.outline!=='none'||v.shadow!=='none').toBeTruthy();return v});
 await check(p,`shell-${w}-${t}-contrast`,`main h1,main p,main label,main button,main a,nav a`,w,t,async()=>{const items=await p.evaluate(()=>[...document.querySelectorAll('main h1,main p,main label,main button,main a,nav[aria-label="Điều hướng chính"] a,nav[aria-label="Điều hướng di động"] a')].filter(e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden').map(e=>{const s=getComputedStyle(e);let n=e;while(n&&getComputedStyle(n).backgroundColor==='rgba(0, 0, 0, 0)')n=n.parentElement;return{tag:e.tagName,text:(e.innerText||'').trim().slice(0,70),fg:s.color,bg:n?getComputedStyle(n).backgroundColor:getComputedStyle(document.body).backgroundColor,size:parseFloat(s.fontSize),role:e.matches('a,button')?'nontext':'text'}}));expect(items.length).toBeGreaterThan(0);const bad=items.map(x=>({...x,ratio:ratio(x.fg,x.bg)})).filter(x=>x.ratio<(x.role==='nontext'?3:4.5));expect(bad,JSON.stringify(bad)).toEqual([]);return{count:items.length,minimum:Math.min(...items.map(x=>ratio(x.fg,x.bg)))}})
}
test('live Vue Phase 1 shell',async({browser})=>{
 fs.mkdirSync(out,{recursive:true});const errors=[],fontResponses=[],externalFonts=[];const c=await browser.newContext({viewport:{width:1440,height:900},locale:'vi-VN',colorScheme:'light'}),p=await c.newPage();
 p.on('pageerror',e=>errors.push({type:'pageerror',message:e.message}));p.on('console',e=>{if(e.type()==='error')errors.push({type:'console',message:e.text()})});p.on('requestfailed',r=>errors.push({type:'requestfailed',message:r.url()+': '+r.failure()?.errorText}));p.on('request',r=>{if(/\.(woff2?|ttf|otf)(\?|$)/i.test(r.url())&&!r.url().startsWith(base+'/'))externalFonts.push(r.url())});p.on('response',r=>{if(/\.(woff2?|ttf|otf)(\?|$)/i.test(r.url()))fontResponses.push({url:r.url(),status:r.status()})});
 try{
  for(const w of [1440,390,320])for(const t of ['light','dark']){await p.setViewportSize({width:w,height:900});await p.emulateMedia({colorScheme:t});await p.goto(base+'/login',{waitUntil:'networkidle'});await expect(p.getByRole('heading',{name:'Cây Gia Phả'})).toBeVisible();await shell(p,w,t)}
  await p.setViewportSize({width:1440,height:900});await p.emulateMedia({colorScheme:'dark'});await p.goto(base+'/login',{waitUntil:'networkidle'});
  await check(p,'demo-amber','[data-testid=demo-login-btn]',1440,'dark',async()=>{const b=p.locator('[data-testid="demo-login-btn"]');await expect(b).toHaveCount(1);const x=await b.evaluate(e=>({bg:getComputedStyle(e).backgroundColor,token:getComputedStyle(document.documentElement).getPropertyValue('--demo-button').trim(),fg:getComputedStyle(e).color}));expect(x.bg).toBe(x.token);expect(ratio(x.fg,x.bg)).toBeGreaterThanOrEqual(4.5);return x});
  await check(p,'fraunces-self-hosted','Fraunces font face + same-origin response',1440,'dark',async()=>{const faces=await p.evaluate(async()=>{await document.fonts.load('600 32px Fraunces','Phả');return[...document.fonts].filter(x=>x.family.includes('Fraunces')).map(x=>({family:x.family,status:x.status}))});const good=fontResponses.filter(x=>x.url.startsWith(base+'/')&&x.status<400);expect(faces.some(x=>x.status==='loaded')).toBeTruthy();expect(good.length).toBeGreaterThan(0);expect(externalFonts).toEqual([]);return{faces,good,externalFonts}});
    "notObserved":{gen1:'NOT OBSERVED: no reachable route provides fixture-backed gen1 chip; production UI was not altered to force one.',gen2:'NOT OBSERVED: no reachable route provides fixture-backed gen2 chip.',gen3:'NOT OBSERVED: no reachable route provides fixture-backed gen3 chip.',gen4:'NOT OBSERVED: no reachable route provides fixture-backed gen4 chip.',authInterstitial:'Observed via public /auth/email/verify route.'},
  await check(p,'theme-live-switch','OS color scheme live switching',1440,'light',async()=>{const b=()=>p.evaluate(()=>getComputedStyle(document.body).backgroundColor),light=await b();await p.emulateMedia({colorScheme:'dark'});const dark=await b();await p.emulateMedia({colorScheme:'light'});const again=await b();expect(dark).not.toBe(light);expect(again).toBe(light);return{light,dark,again}});
  for(const route of ['/tree','/kinship','/feed']){await p.goto(base+route,{waitUntil:'networkidle'});await check(p,`route-${route.slice(1)}`,'main',1440,'light',async()=>{await expect(p.locator('main')).toBeVisible();return{path:new URL(p.url()).pathname,title:await p.title()}})}
  await p.goto(base+'/login',{waitUntil:'networkidle'});await check(p,'demo-flow','demo login button',1440,'light',async()=>{const b=p.locator('[data-testid="demo-login-btn"]');await expect(b).toHaveCount(1);await b.click();await p.waitForURL(/\/tree/,{timeout:12000});const a=p.locator('nav a[aria-current="page"]');await expect(a).toHaveCount(1);return{path:new URL(p.url()).pathname,current:await a.innerText()}});
 }finally{await c.close();fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify({base,cases:rows,errors,fontResponses,externalFonts,unobserved:{genChipVariants:'NOT OBSERVED unless fixture attributes are exposed by reachable Vue route',authInterstitialHover:'NOT OBSERVED unless fixture attributes are exposed by reachable Vue route',preFixBaseline:{genLabelContrast:'1.81–2.14:1',authLinkHoverContrast:'~1.8:1'}},verdict:rows.every(x=>x.status==='PASS')&&!errors.length?'PASS':'FAIL'},null,2))}
 expect(rows.filter(x=>x.status==='FAIL')).toEqual([]);expect(errors).toEqual([]);
});
