const { test: base, expect } = require('@playwright/test');
const test=base.extend({browser: async ({browser},use)=>{const b=await require('@playwright/test').chromium.launch({headless:true});await use(b);await b.close()}});
const fs = require('node:fs');
const path = require('node:path');
const BASE='http://localhost:3456';
const OUT=path.resolve(process.env.ARTIFACTS||path.resolve(__dirname,'../../.agents/tester/RESULTS/apple_phase5_a11y_depth'));
const routes=['tree','member','kinship','feed','account','login'];
const rows=[];
async function demo(page){await page.goto(BASE+'/login',{waitUntil:'domcontentloaded'});const b=page.locator('[data-testid="demo-login-btn"]');if(await b.isVisible().catch(()=>false)){await b.click();await page.waitForTimeout(500)}}
async function ready(page,route){if(route==='login'){await page.goto(BASE+'/login',{waitUntil:'domcontentloaded'});return}await demo(page);let id='';if(route==='member'){const r=await page.request.get(BASE+'/api/v1/members?limit=100');if(r.ok()){const j=await r.json();const items=j.items||j.data?.items||[];id=items[0]?.id||''}if(!id)throw Error('No real demo member id from members API');await page.goto(`${BASE}/members/${id}`,{waitUntil:'domcontentloaded'})}else{await page.goto(BASE+'/'+(route==='account'?'account':route),{waitUntil:'domcontentloaded'})}await page.waitForTimeout(600);if(route==='kinship'){for(const [n,v] of [[1,'An'],[2,'Bình']]){const x=page.locator(`[data-testid="picker-input-${n}"] input`);await x.fill(v);await page.waitForTimeout(250);const op=page.locator(`[data-testid="picker-input-${n}"]`);await op.press('ArrowDown');const opt=page.locator('[role="option"]').first();if(await opt.isVisible().catch(()=>false))await opt.click()}const calc=page.locator('[data-testid="calculate-btn"]');if(await calc.isEnabled().catch(()=>false))await calc.click();await page.waitForTimeout(300)}}
async function focusEvidence(page){await page.evaluate(()=>document.activeElement?.blur());await page.keyboard.press('Tab');const items=[];for(let i=0;i<100;i++){const e=page.locator(':focus-visible').first();if(!(await e.count().catch(()=>0)))break;const info=await e.evaluate(el=>{const s=getComputedStyle(el);const r=el.getBoundingClientRect();return {tag:el.tagName,role:el.getAttribute('role'),name:el.getAttribute('aria-label')||el.innerText?.trim().slice(0,60),selector:el.id?'#'+el.id:el.tagName.toLowerCase(),outline:`${s.outlineStyle} ${s.outlineWidth} ${s.outlineColor}`,shadow:s.boxShadow,rect:{x:r.x,y:r.y,w:r.width,h:r.height},ring:s.outlineStyle!=='none'&&parseFloat(s.outlineWidth)>0||s.boxShadow!=='none'&&s.boxShadow!=='0px 0px 0px 0px'};});items.push(info);await page.keyboard.press('Tab')}return items}
test('Phase 5 accessibility spot-depth on live stack',async({browser})=>{fs.mkdirSync(OUT,{recursive:true});for(const route of routes)for(const view of [{w:1440,h:900,n:'desktop'},{w:390,h:844,n:'mobile'}]){const c=await browser.newContext({viewport:{width:view.w,height:view.h},colorScheme:'light',locale:'vi-VN',serviceWorkers:'block',recordHar:undefined,trace:'off'});const p=await c.newPage();let row={route,viewport:view.n,verdict:'PASS',evidence:`${route}-${view.n}.png`};try{await ready(p,route);const walk=await focusEvidence(p);row.focusCount=walk.length;row.focus=walk;row.invisibleRing=walk.filter(x=>!x.ring);expect(walk.length,'No tabbable/focus-visible elements').toBeGreaterThan(0);row.ringPass=row.invisibleRing.length===0;const cur=await p.locator('[aria-current="page"]').count();row.ariaCurrentCount=cur;expect(cur,'active navigation item aria-current=page').toBeGreaterThan(0);const levels=await p.locator('h1,h2,h3,h4,h5,h6').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>Number(e.tagName.slice(1))));row.headingLevels=levels;row.headingPass=true;for(let i=1;i<levels.length;i++)if(levels[i]>levels[i-1]+1)row.headingPass=false;if(route==='kinship'){const combos=await p.locator('[role=combobox]').evaluateAll(es=>es.map(e=>({id:e.id,controls:e.getAttribute('aria-controls'),expanded:e.getAttribute('aria-expanded')})));row.combos=combos;expect(new Set(combos.map(x=>x.id)).size).toBe(combos.length);for(const x of combos){expect(x.id).toBeTruthy();expect(x.controls).toBeTruthy();expect(await p.locator(`#${CSS.escape(x.controls)}[role="listbox"]`).count()).toBe(1)}}await p.screenshot({path:path.join(OUT,row.evidence),fullPage:true})}catch(e){row.verdict='FAIL';row.error=e.message;try{await p.screenshot({path:path.join(OUT,row.evidence),fullPage:true})}catch{}}rows.push(row);console.log(`ROUTE ${route}|${view.n}|${row.verdict}|${row.evidence}|${row.error||''}`);await c.close()}
// Reduced-motion / dark-mode focused checks.
for(const route of ['login','tree','feed']){const c=await browser.newContext({viewport:{width:390,height:844},colorScheme:'dark',reducedMotion:'reduce',locale:'vi-VN',trace:'off'});const p=await c.newPage();let r={route,probe:'reduced-motion-dark',verdict:'PASS'};try{await ready(p,route);r.motion=await p.locator('body,main,header,nav,[class*="card" i]').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>{const s=getComputedStyle(e);return {selector:e.tagName+'.'+String(e.className).slice(0,60),animationName:s.animationName,transitionDuration:s.transitionDuration}}));r.long=r.motion.filter(x=>x.animationName!=='none'||x.transitionDuration.split(',').some(d=>parseFloat(d)>1));expect(r.long).toEqual([]);await p.screenshot({path:path.join(OUT,`${route}-reduced-dark.png`),fullPage:true})}catch(e){r.verdict='FAIL';r.error=e.message}rows.push(r);console.log(`MOTION ${route}|${r.verdict}|${r.error||''}`);await c.close()}
const dir=process.env.ARTIFACTS||OUT;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify(rows,null,2));});
