const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const MIN_AA=4.5,CENTER_DELTA_PX=2,DESKTOP_MIN=960,CARD_MIN=320,CARD_MAX=400,SMALL_WIDTHS=[390,320],HEIGHTS=[844,700],THEMES=['light','dark'];
const base=process.env.APPLE_PHASE2_BASE;if(!base||!/^http:\/\/127\.0\.0\.1:1[0-9]{4}$/.test(base))throw Error('APPLE_PHASE2_BASE required (http://127.0.0.1:1xxxx)');
const out=process.env.APPLE_PHASE2_ARTIFACTS||path.resolve(__dirname,'../../.agents/tester/RESULTS/apple_phase2_login_browser');fs.mkdirSync(out,{recursive:true});
const USER={id:'e2e',display_name:'E2E',is_demo:false,created_at:'2026-01-01T00:00:00Z'},PROFILE={User:USER,Identities:[],Contacts:[]};
async function staged(ctx,{hang='',status=200,me=401}={}){await ctx.route('**/api/**',r=>{const u=r.request().url();if(/\/me(?:\?|$)/.test(u))return r.fulfill({status:me,contentType:'application/json',body:JSON.stringify(me===200?PROFILE:{code:'UNAUTHENTICATED'})});if(hang&&u.includes(hang))return new Promise(()=>{});const providers=u.includes('/auth/providers');return r.fulfill({status:providers?200:(u.includes('/auth/email/magic-link')||u.includes('/auth/demo')?status:404),contentType:'application/json',body:JSON.stringify(providers?{providers:[{id:'google',name:'Google'},{id:'facebook',name:'Facebook'},{id:'zalo',name:'Zalo'}]}:{})});});}
async function context(browser,w=1440,h=900,theme='light',opts={}){const c=await browser.newContext({viewport:{width:w,height:h},locale:'vi-VN',colorScheme:theme});await staged(c,opts);return c;}
async function monitor(p){const errors=[],responses=[];p.on('response',r=>responses.push({url:r.url(),status:r.status()}));p.on('pageerror',e=>errors.push({message:e.message,url:null,status:null}));p.on('console',m=>{if(m.type()==='error'){const loc=m.location().url||null,x=responses.find(r=>r.url===loc)||responses.find(r=>m.text().includes(r.url));errors.push({message:m.text(),url:x?.url||loc,status:x?.status??null});}});return errors;}
const whitelist=e=>e.status===401&&/\/api\/v1\/me(?:\?|$)/.test(e.url||'');let current={},cases=[];
test.afterEach(async({},info)=>{const errors=Array.isArray(current.errors)?current.errors:[],r={title:info.title,status:info.status,expectedStatus:info.expectedStatus,console:{all:errors,whitelisted:errors.filter(whitelist),rejected:errors.filter(e=>!whitelist(e))},proof:current.proof||{},visual:current.visual||[]};cases.push(r);await fs.promises.writeFile(path.join(out,'case-'+info.title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.json'),JSON.stringify(r,null,2));await fs.promises.writeFile(path.join(out,'summary.json'),JSON.stringify({cases},null,2));current={};});
const SWEEP=`(()=>{const rgb=s=>{let m=s.match(/[\\d.]+/g)||[0,0,0];return[+m[0],+m[1],+m[2],m.length>3?+m[3]:1]},lum=c=>{let a=c.slice(0,3).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*a[0]+.7152*a[1]+.0722*a[2]},out=[];for(const e of document.querySelectorAll('h1,h2,h3,p,span,a,button,label'))if(e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden'&&(e.innerText||'').trim()&&!e.closest('[aria-hidden=true]')){let f=rgb(getComputedStyle(e).color),b=[255,255,255],n=e;while(n){let c=rgb(getComputedStyle(n).backgroundColor);if(c[3]){b=b.map((v,i)=>c[i]*c[3]+v*(1-c[3]));if(c[3]===1)break}n=n.parentElement}let F=lum(f),B=lum(b);out.push({text:e.innerText.trim().slice(0,60),ratio:(Math.max(F,B)+.05)/(Math.min(F,B)+.05)})}return out})()`;
async function visual(p){const a=await p.evaluate(SWEEP);expect(a.length).toBeGreaterThan(0);expect(a.filter(x=>!Number.isFinite(x.ratio)||x.ratio<MIN_AA)).toEqual([]);const o=await p.evaluate(()=>({doc:document.documentElement.scrollWidth-document.documentElement.clientWidth,body:document.body.scrollWidth-document.body.clientWidth}));expect(o.doc).toBeLessThanOrEqual(0);expect(o.body).toBeLessThanOrEqual(0);await p.evaluate(()=>document.activeElement?.blur());await p.keyboard.press('Tab');await p.waitForTimeout(250);const f=await p.locator(':focus-visible').first().evaluate(e=>{const s=getComputedStyle(e);return s.outlineStyle!=='none'||s.boxShadow!=='none'});expect(f).toBeTruthy();return{lowest:a.slice().sort((x,y)=>x.ratio-y.ratio).slice(0,3),overflow:o,focus:f};}
async function open(c,url='/login'){const p=await c.newPage(),errors=monitor(p);await p.goto(base+url,{waitUntil:'domcontentloaded'});return{p,errors};}
test('login idle desktop, panel contracts, amber demo',async({browser})=>{const c=await context(browser),{p,errors}=await open(c);await expect(p.locator('[data-testid="login-intro"]')).toBeVisible();await expect(p.locator('main div.bg-card')).toBeVisible();const x=await p.evaluate(()=>({root:getComputedStyle(document.querySelector('main').firstElementChild).display,intro:getComputedStyle(document.querySelector('[data-testid="login-intro"]')).display,heading:!!document.querySelector('[data-testid="login-intro"] p.font-display'),copy:!!document.querySelector('[data-testid="login-intro"] p.text-sm')}));expect(x.root).toBe('grid');expect(x.intro).toBe('flex');const card=await p.locator('main div.bg-card').evaluate(e=>({maxWidth:getComputedStyle(e).maxWidth,width:e.getBoundingClientRect().width}));expect(card.maxWidth).toBe('400px');expect(card.width).toBeGreaterThan(CARD_MIN);expect(card.width).toBeLessThanOrEqual(CARD_MAX);expect(x.heading&&x.copy).toBeTruthy();for(const n of ['google','facebook','zalo'])await expect(p.getByRole('button',{name:new RegExp(n,'i')})).toBeVisible();await expect(p.locator('#magic-link-email')).toBeVisible();await expect(p.getByRole('button',{name:/Gửi liên kết đăng nhập/})).toBeVisible();const d=p.locator('[data-testid="demo-login-btn"]');await expect(d).toBeVisible();await expect(d).toContainText('bản dùng thử');const demo=await d.evaluate(e=>({background:getComputedStyle(e).backgroundColor,token:getComputedStyle(document.documentElement).getPropertyValue('--demo-button').trim()}));expect(demo.background).toBeTruthy();expect(demo.token).toBeTruthy();current={errors:Array.from(errors||[]),proof:{card,demoAmber:demo}};expect(Array.from(errors||[]).filter(e=>!whitelist(e))).toEqual([]);await c.close();});
test('magic link pending/sent/error, validation, verified, demo pending',async({browser})=>{const proof={},all=[];let c=await context(browser,1440,900,'light',{hang:'/auth/email/magic-link'}),{p,errors}=await open(c);all.push(...Array.from(errors||[]));await p.locator('#magic-link-email').fill('a@example.test');await p.getByRole('button',{name:/Gửi liên kết đăng nhập/}).click();await expect(p.locator('form button[type=submit]')).toBeDisabled();await expect(p.locator('form input')).toBeDisabled();proof.inFlightDisabled=true;await c.close();c=await context(browser,1440,900,'light',{status:200});({p,errors}=await open(c));all.push(...Array.from(errors||[]));await p.locator('#magic-link-email').fill('a@example.test');await p.getByRole('button',{name:/Gửi liên kết đăng nhập/}).click();await await expect(p.getByText(/đã gửi liên kết đăng nhập/i).last()).toBeVisible();proof.sentBanner=true;await c.close();c=await context(browser);({p,errors}=await open(c));all.push(...Array.from(errors||[]));await p.getByRole('button',{name:/Gửi liên kết đăng nhập/}).click();await expect(p.locator('form').getByText(/email/i).first()).toBeVisible();proof.validationError=true;await c.close();c=await context(browser,1440,900,'light',{status:500});({p,errors}=await open(c));all.push(...Array.from(errors||[]));await p.locator('#magic-link-email').fill('a@example.test');await p.getByRole('button',{name:/Gửi liên kết đăng nhập/}).click();await expect(p.getByText(/thử lại|lỗi|không thể/i).first()).toBeVisible();proof.apiToast=true;await c.close();c=await context(browser);({p,errors}=await open(c,'/login?verified=1'));all.push(...Array.from(errors||[]));await expect(p.getByText(/Email của bạn đã được xác thực thành công/)).toBeVisible();proof.verifiedNotice=true;await c.close();c=await context(browser,1440,900,'light',{hang:'/auth/demo'});({p,errors}=await open(c));all.push(...Array.from(errors||[]));await p.locator('[data-testid="demo-login-btn"]').click();await expect(p.locator('[data-testid="demo-login-btn"] svg.animate-spin')).toBeVisible();proof.demoPending=true;current={errors:Array.from(all),proof};expect(Array.from(all).filter(e=>!whitelist(e))).toEqual([]);await c.close();});
test('authenticated guest guard redirects login to tree',async({browser})=>{const c=await context(browser,1440,900,'light',{me:200}),{p,errors}=await open(c);await expect.poll(()=>new URL(p.url()).pathname).toBe('/tree');current={errors:Array.from(errors||[]),proof:{redirect:new URL(p.url()).pathname}};await c.close();});
test('960 breakpoint edge layout',async({browser})=>{const proof={},all=[];for(const w of [DESKTOP_MIN,DESKTOP_MIN-1]){const c=await context(browser,w,700),{p,errors}=await open(c);all.push(...Array.from(errors||[]));await expect(p.locator('main div.bg-card')).toBeVisible();const z=await p.evaluate(()=>{const r=document.querySelector('main').firstElementChild,i=document.querySelector('[data-testid="login-intro"]'),q=document.querySelector('main div.bg-card'),b=q.getBoundingClientRect();return{root:getComputedStyle(r).display,intro:getComputedStyle(i).display,delta:Math.abs(b.left+b.width/2-innerWidth/2),card:{maxWidth:getComputedStyle(q).maxWidth,width:b.width}}});proof[w]=z;if(w===960){expect(z.root).toBe('grid');expect(z.intro).toBe('flex');expect(z.card.maxWidth).toBe('400px');expect(z.card.width).toBeGreaterThan(CARD_MIN);expect(z.card.width).toBeLessThanOrEqual(CARD_MAX)}else{expect(z.root).toBe('flex');expect(z.intro).toBe('none');expect(z.delta).toBeLessThanOrEqual(CENTER_DELTA_PX)}await c.close();}current={errors:Array.from(all),proof:{breakpoint:proof}};});
test('small light/dark responsive visual, contrast, focus, errors',async({browser})=>{const visualProof=[],all=[];for(const theme of THEMES)for(let i=0;i<SMALL_WIDTHS.length;i++){const c=await context(browser,SMALL_WIDTHS[i],HEIGHTS[i],theme),{p,errors}=await open(c);all.push(...Array.from(errors||[]));await expect(p.locator('main div.bg-card')).toBeVisible();visualProof.push({theme,width:SMALL_WIDTHS[i],...(await visual(p))});expect(Array.from(errors||[]).filter(e=>!whitelist(e))).toEqual([]);await c.close();}current={errors:Array.from(all),visual:visualProof};});
