const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const MIN_AA = 4.5, CENTER_DELTA_PX = 2, DESKTOP_MIN = 960, CARD_MIN = 320, CARD_MAX = 400, SMALL_WIDTHS = [390, 320], HEIGHTS = [844, 700], THEMES = ['light', 'dark'];
const base = process.env.APPLE_PHASE2_BASE;
if (!base || !/^http:\/\/127\.0\.0\.1:1[0-9]{4}$/.test(base)) throw new Error('APPLE_PHASE2_BASE required (http://127.0.0.1:1xxxx)');
const out = process.env.APPLE_PHASE2_ARTIFACTS || path.resolve(__dirname, '../../.agents/tester/RESULTS/apple_phase2_login_browser'); fs.mkdirSync(out, {recursive:true});
const USER={id:'e2e',display_name:'E2E',is_demo:false,created_at:'2026-01-01T00:00:00Z'}, PROFILE={User:USER,Identities:[],Contacts:[]};
async function staged(ctx, {hang='', status=200, me=401}={}) { await ctx.route('**/api/**', r=>{const u=r.request().url(); if(/\/me(?:\?|$)/.test(u)) return r.fulfill({status:me,contentType:'application/json',body:JSON.stringify(me===200?PROFILE:{code:'UNAUTHENTICATED'})}); if(hang && u.includes(hang)) return new Promise(()=>{}); return r.fulfill({status:u.includes('/auth/providers')?200:(u.includes('/auth/email/magic-link')||u.includes('/auth/demo')?status:404),contentType:'application/json',body:JSON.stringify(u.includes('/auth/providers')?{providers:[{id:'google',name:'Google'},{id:'facebook',name:'Facebook'},{id:'zalo',name:'Zalo'}]}:{})}); }); }
async function context(browser,w=1440,h=900,theme='light',opts={}) { const c=await browser.newContext({viewport:{width:w,height:h},locale:'vi-VN',colorScheme:theme}); await staged(c,opts); return c; }
async function monitor(page){const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!(/Failed to load resource/.test(m.text())&&/\/me(?:\?|$)/.test(m.location().url||'')))errors.push(m.text())});return errors;}
const CONTRAST=`(() => {const rgb=s=>{let m=s.match(/[\\d.]+/g);return m&&m.length>=3?[+m[0],+m[1],+m[2],m.length>3?+m[3]:1]:[0,0,0,1]},lum=c=>{let a=c.slice(0,3).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*a[0]+.7152*a[1]+.0722*a[2]},comp=(a,b)=>a.slice(0,3).map((v,i)=>v*a[3]+b[i]*(1-a[3]));return [...document.querySelectorAll('main h1,main h2,main p,main span,main a,main button,main label')].filter(e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden'&&(e.innerText||'').trim()&&!e.closest('[aria-hidden=true]')).map(e=>{let fg=rgb(getComputedStyle(e).color),b=[255,255,255],n=e;while(n){let x=rgb(getComputedStyle(n).backgroundColor);if(x[3]){b=comp(x,b);if(x[3]===1)break}n=n.parentElement}let L=lum(fg),B=lum(b),ratio=(Math.max(L,B)+.05)/(Math.min(L,B)+.05);return {text:e.innerText.trim().slice(0,60),ratio}})})()`;
async function visual(p){const a=await p.evaluate(CONTRAST);expect(a.length).toBeGreaterThan(0);expect(a.filter(x=>!Number.isFinite(x.ratio)||x.ratio<MIN_AA)).toEqual([]);const ov=await p.evaluate(()=>({doc:document.documentElement.scrollWidth-document.documentElement.clientWidth,body:document.body.scrollWidth-document.body.clientWidth}));expect(ov.doc).toBeLessThanOrEqual(0);expect(ov.body).toBeLessThanOrEqual(0);await p.evaluate(()=>document.activeElement?.blur());await p.keyboard.press('Tab');const f=await p.locator(':focus-visible').first().evaluate(e=>{let s=getComputedStyle(e);return s.outlineStyle!=='none'||s.boxShadow!=='none'});expect(f).toBeTruthy();}
async function open(c,url='/login'){const p=await c.newPage(),errors=monitor(p);await p.goto(base+url,{waitUntil:'domcontentloaded'});return {p,errors};}
test('login idle desktop, panel contracts, amber demo',async({browser})=>{const c=await context(browser),{p,errors}=await open(c);await expect(p.locator('[data-testid="login-intro"]')).toBeVisible();const x=await p.evaluate(()=>({root:getComputedStyle(document.querySelector('main').firstElementChild).display,intro:getComputedStyle(document.querySelector('[data-testid="login-intro"]')).display,card:document.querySelector('main .bg-card'),heading:!!document.querySelector('[data-testid="login-intro"] p.font-display'),copy:!!document.querySelector('[data-testid="login-intro"] p.text-sm')}));expect(x.root).toBe('grid');expect(x.intro).toBe('flex');expect(await x.card.evaluate(e=>getComputedStyle(e).maxWidth)).toBe('400px');expect(await x.card.evaluate(e=>e.getBoundingClientRect().width)).toBeGreaterThan(CARD_MIN);expect(await x.card.evaluate(e=>e.getBoundingClientRect().width)).toBeLessThanOrEqual(CARD_MAX);expect(x.heading&&x.copy).toBeTruthy();for(const n of ['google','facebook','zalo']) await expect(p.getByRole('button',{name:new RegExp(n,'i')})).toBeVisible();await expect(p.locator('#magic-link-email')).toBeVisible();await expect(p.getByRole('button',{name:/Gửi liên kết đăng nhập/})).toBeVisible();const d=p.locator('[data-testid="demo-login-btn"]');await expect(d).toBeVisible();await expect(d).toContainText('bản dùng thử');const bg=await d.evaluate(e=>({c:getComputedStyle(e).backgroundColor,t:getComputedStyle(document.documentElement).getPropertyValue('--demo-button').trim()}));expect(bg.t).toBeTruthy();expect(bg.c).toBeTruthy();expect(errors).toEqual([]);await c.close();});
test('magic link pending/sent/error, validation, verified, demo pending',async({browser})=>{let c=await context(browser,1440,900,'light',{hang:'/auth/email/magic-link'}),{p,errors}=await open(c);await p.locator('#magic-link-email').fill('a@example.test');await p.getByRole('button',{name:/Gửi liên kết đăng nhập/}).click();await expect(p.locator('form button[type=submit]')).toBeDisabled();await expect(p.locator('form input')).toBeDisabled();await c.close();c=await context(browser,1440,900,'light',{status:200});({p,errors}=await open(c));await p.locator('#magic-link-email').fill('a@example.test');await p.getByRole('button',{name:/Gửi liên kết đăng nhập/}).click();await expect(p.locator('.magic-sent')).toBeVisible().catch(async()=>expect(p.getByText('Đã gửi liên kết đăng nhập')).toBeVisible());await c.close();c=await context(browser);({p}=await open(c));await p.getByRole('button',{name:/Gửi liên kết đăng nhập/}).click();await expect(p.getByText('Vui lòng nhập địa chỉ email.')).toBeVisible();await c.close();c=await context(browser,1440,900,'light',{status:500});({p}=await open(c));await p.locator('#magic-link-email').fill('a@example.test');await p.getByRole('button',{name:/Gửi liên kết đăng nhập/}).click();await expect(p.getByText(/thử lại|lỗi|không thể/i).first()).toBeVisible();await c.close();c=await context(browser);({p}=await open(c,'/login?verified=1'));await expect(p.getByText(/Email của bạn đã được xác thực thành công/)).toBeVisible();await c.close();c=await context(browser,1440,900,'light',{hang:'/auth/demo'});({p}=await open(c));await p.locator('[data-testid="demo-login-btn"]').click();await expect(p.locator('[data-testid="demo-login-btn"] svg.animate-spin')).toBeVisible();await expect(errors).toEqual([]);await c.close();});
test('authenticated guest guard redirects login to tree',async({browser})=>{const c=await context(browser,1440,900,'light',{me:200});const {p}=await open(c);await expect.poll(()=>new URL(p.url()).pathname).toBe('/tree');await c.close();});
test('960 breakpoint edge layout',async({browser})=>{for(const w of [DESKTOP_MIN,DESKTOP_MIN-1]){const c=await context(browser,w,700),{p}=await open(c);const z=await p.evaluate(()=>{let r=document.querySelector('main').firstElementChild,i=document.querySelector('[data-testid="login-intro"]'),q=document.querySelector('main .bg-card'),b=q.getBoundingClientRect();return{root:getComputedStyle(r).display,intro:getComputedStyle(i).display,delta:Math.abs(b.left+b.width/2-innerWidth/2)}});if(w===DESKTOP_MIN){expect(z.root).toBe('grid');expect(z.intro).toBe('flex')}else{expect(z.root).toBe('flex');expect(z.intro).toBe('none');expect(z.delta).toBeLessThanOrEqual(CENTER_DELTA_PX)}await c.close();}});
test('small light/dark responsive visual, contrast, focus, errors',async({browser})=>{for(const theme of THEMES)for(let i=0;i<SMALL_WIDTHS.length;i++){const c=await context(browser,SMALL_WIDTHS[i],HEIGHTS[i],theme),{p,errors}=await open(c);await visual(p);expect(errors).toEqual([]);await c.close();}});
