const {test,expect}=require('@playwright/test');const fs=require('node:fs'),path=require('node:path');
const MIN_AA=4.5,SMALL_WIDTHS=[390,320],HEIGHTS=[844,700],THEMES=['light','dark'],HOLD_MS=1600,REDIRECT_MS=1500,WAIT_MS=2500;
const base=process.env.APPLE_PHASE2_BASE;if(!base||!/^http:\/\/127\.0\.0\.1:1[0-9]{4}$/.test(base))throw Error('APPLE_PHASE2_BASE required (http://127.0.0.1:1xxxx)');const out=process.env.APPLE_PHASE2_ARTIFACTS||path.resolve(__dirname,'../../.agents/tester/RESULTS/apple_phase2_oauth_callback_browser');fs.mkdirSync(out,{recursive:true});const PROFILE={User:{id:'e2e',display_name:'E2E',is_demo:false,created_at:'2026-01-01T00:00:00Z'},Identities:[],Contacts:[]};
const MSG={invalid_state:'Phiên đăng nhập không hợp lệ hoặc đã hết hạn. Vui lòng thử lại.',already_linked:'Tài khoản mạng xã hội này đã được liên kết với tài khoản khác.',provider_error:'Không thể kết nối với nhà cung cấp đăng nhập. Vui lòng thử lại sau.',demo_restricted:'Chức năng này bị hạn chế trong chế độ demo.',server_error:'Đã xảy ra lỗi hệ thống. Vui lòng thử lại sau.'},PROVIDERS=['google','facebook','zalo'];
async function ctx(browser,me=401,w=1440,h=900,theme='light'){const c=await browser.newContext({viewport:{width:w,height:h},locale:'vi-VN',colorScheme:theme});await c.route('**/api/**',r=>{if(/\/me(?:\?|$)/.test(r.request().url()))return r.fulfill({status:me,contentType:'application/json',body:JSON.stringify(me===200?PROFILE:{code:'UNAUTHENTICATED'})});return r.fulfill({status:404,contentType:'application/json',body:'{}'});});return c;}
async function open(c,url){const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!(/Failed to load resource/.test(m.text())&&/\/me(?:\?|$)/.test(m.location().url||'')))errors.push(m.text())});await p.goto(base+url,{waitUntil:'domcontentloaded'});return{p,errors};}
const sweep=`(()=>{const lum=s=>{const m=s.match(/[\\d.]+/g)||[0,0,0],a=m.slice(0,3).map(v=>+v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*a[0]+.7152*a[1]+.0722*a[2]},parse=s=>{let m=s.match(/[\\d.]+/g)||[0,0,0];return[+m[0],+m[1],+m[2],m.length>3?+m[3]:1]},out=[];for(const e of document.querySelectorAll('h1,h2,h3,p,span,a,button'))if(e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden'&&(e.innerText||'').trim()&&!e.closest('[aria-hidden=true]')){let fg=parse(getComputedStyle(e).color),bg=[255,255,255],n=e;while(n){let x=parse(getComputedStyle(n).backgroundColor);if(x[3]){bg=x.slice(0,3).map((v,i)=>v*x[3]+bg[i]*(1-x[3]));if(x[3]===1)break}n=n.parentElement}let a=lum('rgb('+fg.slice(0,3)+')'),b=lum('rgb('+bg+')');out.push({text:e.innerText.trim().slice(0,40),ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)})}return out})()`;
async function visual(p){const a=await p.evaluate(sweep);expect(a.length).toBeGreaterThan(0);expect(a.filter(x=>!Number.isFinite(x.ratio)||x.ratio<MIN_AA)).toEqual([]);const o=await p.evaluate(()=>[document.documentElement,document.body].map(x=>x.scrollWidth-x.clientWidth));expect(o.every(x=>x<=0)).toBeTruthy();await p.evaluate(()=>document.activeElement?.blur());await p.keyboard.press('Tab');const f=await p.locator(':focus-visible').first().evaluate(e=>{const s=getComputedStyle(e);return s.outlineStyle!=='none'||s.boxShadow!=='none'});expect(f).toBeTruthy();}
async function success(browser,provider,me,freeze){const c=await ctx(browser,me),p=await c.newPage();if(freeze)await p.clock.pauseAt(new Date('2026-09-27T12:00:00Z'));await p.goto(base+`/auth/oauth/callback?oauth_linked=${provider}`,{waitUntil:'domcontentloaded'});await expect(p.locator('[data-testid="oauth-success"]')).toBeVisible();await expect(p.locator('[data-testid="status-disc-success"]')).toBeVisible();const name=provider==='zalo'?'Zalo':provider[0].toUpperCase()+provider.slice(1);await expect(p.locator('[data-testid="oauth-message"]')).toHaveText(`Đã liên kết thành công tài khoản ${name} với Cây Gia Phả.`);if(freeze){await p.waitForTimeout(HOLD_MS+100);expect(new URL(p.url()).pathname).toBe('/auth/oauth/callback')}else await expect.poll(()=>new URL(p.url()).pathname,{timeout:WAIT_MS}).toBe(me===200?'/account':'/login');await c.close();}
test('bare callback never presents invented working state',async({browser})=>{const c=await ctx(browser),{p,errors}=await open(c,'/auth/oauth/callback');await expect(p.locator('[data-testid="oauth-error"]')).toBeVisible();await expect(p.locator('[data-testid="status-disc-working"]')).toHaveCount(0);await expect(p.locator('[data-testid="status-disc-success"], [data-testid="status-disc-error"]')).toHaveCount(1);expect(errors).toEqual([]);await c.close();});
test('authenticated success, frozen window and redirect per provider',async({browser})=>{for(const p of PROVIDERS){await success(browser,p,200,true);await success(browser,p,200,false);}});
test('guest success fallback redirects login',async({browser})=>{await success(browser,'google',401,false);});
test('five known OAuth errors map exact Vietnamese copy',async({browser})=>{for(const code of Object.keys(MSG)){const c=await ctx(browser),{p,errors}=await open(c,`/auth/oauth/callback?oauth_error=${code}`);await expect(p.locator('[data-testid="oauth-error"]')).toBeVisible();await expect(p.locator('[data-testid="status-disc-error"]')).toBeVisible();await expect(p.locator('[data-testid="oauth-message"]')).toHaveText(MSG[code]);if(code==='demo_restricted'){await expect(p.locator('[data-testid="oauth-error"]')).toContainText(/demo/i);const bg=await p.locator('[data-testid="status-disc-error"]').evaluate(e=>getComputedStyle(e).backgroundColor);expect(bg).not.toBe('rgba(0, 0, 0, 0)')}expect(errors).toEqual([]);await c.close();}});
test('unknown error falls back without crash or working state',async({browser})=>{const c=await ctx(browser),{p,errors}=await open(c,'/auth/oauth/callback?oauth_error=nonsense_code');await expect(p.locator('[data-testid="oauth-error"]')).toBeVisible();await expect(p.locator('[data-testid="oauth-message"]')).toHaveText(MSG.server_error);await expect(p.locator('[data-testid="status-disc-working"]')).toHaveCount(0);expect(errors).toEqual([]);await c.close();});
test('success and error responsive light/dark visual checks',async({browser})=>{for(const theme of THEMES)for(let i=0;i<SMALL_WIDTHS.length;i++)for(const state of ['error','success']){const c=await ctx(browser,401,SMALL_WIDTHS[i],HEIGHTS[i],theme),url=state==='error'?'/auth/oauth/callback?oauth_error=provider_error':'/auth/oauth/callback?oauth_linked=google',{p,errors}=await open(c,url);await expect(p.locator(`[data-testid="oauth-${state}"]`)).toBeVisible();await visual(p);expect(errors).toEqual([]);await c.close();}});
