const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const BASE='http://localhost:3456',OUT=path.resolve(__dirname,'../../.agents/tester/RESULTS/apple_phase5_console_hygiene');
const rows=[];
async function demo(p){await p.goto(BASE+'/login');await p.locator('[data-testid="demo-login-btn"]').click();await p.waitForTimeout(350)}
function watch(p,r){p.on('console',m=>r.events.push({type:m.type(),text:m.text()}));p.on('pageerror',e=>r.pageerrors.push(String(e)));p.on('requestfailed',q=>r.failed.push({url:q.url(),error:q.failure()?.errorText}));p.on('response',q=>r.responses.push({url:q.url(),status:q.status()}))}
test('Phase 5 live console and 5xx hygiene',async({browser,request})=>{
 const checks=[];for(const [u,label] of [['/healthz','healthz'],['/api/v1/health','health'],['/api/v1/families','families'],['/static/avatars/avatar-m1.svg','avatar']]){const x=await request.get(BASE+u);checks.push({label,status:x.status(),body:label==='health'?await x.text():''})}
 const c=await browser.newContext({viewport:{width:1440,height:900},locale:'vi-VN'}),p=await c.newPage();await demo(p);const ml=await p.request.get(BASE+'/api/v1/members?limit=100');let id='';if(ml.ok()){const j=await ml.json();id=(j.items||j.data?.items||[])[0]?.id||''}await c.close();
 const routes=['/','/login','/auth/email/verify','/auth/oauth/callback','/phase5-nonexistent-404','/tree',...(id?[`/members/${id}`]:[]),'/kinship','/feed','/account'];
 for(const route of routes){const ctx=await browser.newContext({viewport:{width:1440,height:900},locale:'vi-VN'}),pg=await ctx.newPage(),r={route,events:[],responses:[],pageerrors:[],failed:[],verdict:'PASS'};watch(pg,r);try{
 if(['/tree','/kinship','/feed','/account'].includes(route)||route.startsWith('/members/'))await demo(pg);await pg.goto(BASE+route,{waitUntil:'domcontentloaded'});await pg.waitForTimeout(500);
 if(route==='/members/'+id){for(const label of [/bài viết|hoạt động/i,/thông tin|chi tiết/i]){const t=pg.getByRole('tab',{name:label}).first();if(await t.isVisible().catch(()=>false))await t.click()}}
 if(route==='/kinship'){for(const [n,v] of [[1,'An'],[2,'Bình']]){const x=pg.locator(`[data-testid="picker-input-${n}"]`);if(await x.isVisible().catch(()=>false)){await x.click();await x.fill(v).catch(()=>{});await pg.waitForTimeout(250);const opt=pg.locator('[role="option"]').first();if(await opt.isVisible().catch(()=>false))await opt.click()}}const calc=pg.locator('[data-testid="calculate-btn"]');if(await calc.isEnabled().catch(()=>false))await calc.click()}
 if(route==='/feed'){const more=pg.getByRole('button',{name:/tải thêm|xem thêm|load more/i});if(await more.isVisible().catch(()=>false))await more.click();const box=pg.locator('textarea').first();if(await box.isVisible().catch(()=>false))await box.fill('console hygiene probe')}
 if(route==='/account'){for(const name of [/liên kết|identity|tài khoản/i,/liên hệ|contact/i]){const tab=pg.getByRole('tab',{name}).first();if(await tab.isVisible().catch(()=>false))await tab.click()}}
 if(route==='/tree'){await pg.unrouteAll();const target=pg.waitForResponse(q=>q.url().includes('/api/v1/families')&&q.request().method()==='GET');await pg.route('**/api/v1/families',async q=>q.fulfill({status:500,contentType:'application/json',body:'{"message":"staged 500"}'}));await pg.reload();await target.catch(()=>{});await pg.waitForTimeout(250);await pg.unroute('**/api/v1/families');r.forced500Ui=await pg.getByText('Không thể tải cây gia phả').count()>0;}
 await pg.waitForTimeout(120);r.consoleErrors=r.events.filter(e=>e.type==='error'&&!/status of 401 \(Unauthorized\)/.test(e.text)&&!(route==='/tree'&&e.text.includes('status of 500')));r.consoleWarnings=r.events.filter(e=>e.type==='warning');r.real5xx=r.responses.filter(x=>x.status>=500&&!x.url.includes('/api/'));r.staged5xx=route==='/tree'?r.responses.filter(x=>x.status===500&&x.url.includes('/api/')):[];r.verdict=(r.consoleErrors.length||r.pageerrors.length||r.failed.length||r.real5xx.length)?'FAIL':'PASS';if(route==='/tree'&&!r.forced500Ui)r.harnessNote='staged API returned 500 but app error state not observed';
 }catch(e){r.verdict='FAIL';r.error=String(e)}rows.push(r);console.log(`ROUTE ${route}|${r.consoleErrors?.length||0}|${r.consoleWarnings?.length||0}|${r.real5xx?.length||0}|${[...new Set(r.responses.map(x=>x.status))].join(',')}|${r.verdict}`);await ctx.close()}
 const detail=id?await request.get(BASE+`/api/v1/members/${id}`):null;checks.push({label:'member-detail',status:detail?.status()||0,memberId:id});fs.writeFileSync(path.join(OUT,'results.json'),JSON.stringify({checks,rows},null,2));expect(checks.find(x=>x.label==='healthz').status).toBe(200);expect(checks.find(x=>x.label==='health').body).toContain('"db":"up"');expect(checks.find(x=>x.label==='families').status).toBe(200);expect(checks.find(x=>x.label==='member-detail').status).toBe(200);expect(checks.find(x=>x.label==='avatar').status).toBe(200);expect(rows.filter(x=>x.verdict==='FAIL')).toEqual([])
});
