// Independent Phase 3 misc verification; source anchors: NotFoundView.vue:16-54, LoginView.vue:151-152.
const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const base=process.env.APPLE_PHASE3_MISC_BASE;
if(!base) throw Error('APPLE_PHASE3_MISC_BASE required');
const out=process.env.APPLE_PHASE3_MISC_ARTIFACTS||path.resolve(__dirname,'../../.agents/tester/RESULTS/apple_phase3_misc_browser');
fs.mkdirSync(out,{recursive:true});
const MIN_AA=4.5, sizes=[[1440,900],[390,844],[320,568]], themes=['light','dark'];
const sweep=`(()=>{const lum=s=>{const m=s.match(/[\\d.]+/g)||[0,0,0],a=m.slice(0,3).map(v=>+v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*a[0]+.7152*a[1]+.0722*a[2]},parse=s=>{let m=s.match(/[\\d.]+/g)||[0,0,0];return[+m[0],+m[1],+m[2],m.length>3?+m[3]:1]},out=[];for(const e of document.querySelectorAll('h1,h2,h3,p,span,a,button'))if(e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden'&&(e.innerText||'').trim()&&!e.closest('[aria-hidden=true]')){let fg=parse(getComputedStyle(e).color),bg=[255,255,255],n=e;while(n){let x=parse(getComputedStyle(n).backgroundColor);if(x[3]){bg=x.slice(0,3).map((v,i)=>v*x[3]+bg[i]*(1-x[3]));if(x[3]===1)break}n=n.parentElement}let a=lum('rgb('+fg.slice(0,3)+')'),b=lum('rgb('+bg+')');out.push({text:e.innerText.trim().slice(0,40),ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)})}return out})()`;
async function visual(page){const ratios=await page.evaluate(sweep);expect(ratios.length).toBeGreaterThan(0);expect(ratios.filter(x=>!Number.isFinite(x.ratio)||x.ratio<MIN_AA)).toEqual([]);const overflow=await page.evaluate(()=>[document.documentElement,document.body].some(e=>e.scrollWidth>e.clientWidth));expect(overflow).toBeFalsy();await page.evaluate(()=>document.activeElement?.blur());await page.keyboard.press('Tab');const focus=await page.locator(':focus-visible').first().evaluate(e=>{const s=getComputedStyle(e);return s.outlineStyle!=='none'||s.boxShadow!=='none'});expect(focus).toBeTruthy();return{lowest:ratios.slice().sort((a,b)=>a.ratio-b.ratio).slice(0,3),overflow,focus};}
for(const [w,h] of sizes)for(const theme of themes)test(`404 NotFoundView ${w}x${h} ${theme}`,async({page})=>{await page.setViewportSize({width:w,height:h});await page.emulateMedia({colorScheme:theme});await page.setExtraHTTPHeaders({'Accept-Language':'vi-VN'});const errors=[],responses=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>responses.push({url:r.url(),status:r.status()}));page.on('console',m=>{if(m.type()==='error'){const u=m.location().url||'';const r=responses.find(x=>x.url===u);if(!(r?.status===401&&/\/api\/v1\/me(?:\?|$)/.test(r.url)))errors.push(m.text())}});await page.goto(base+'/no-such-route',{waitUntil:'domcontentloaded'});const nf=page.getByTestId('not-found');await expect(nf).toBeVisible();await expect(page.getByText('404',{exact:true})).toBeVisible();await expect(page.getByText('Đường dẫn không tồn tại')).toBeVisible();await expect(page.getByRole('heading',{name:'Không tìm thấy trang'})).toBeVisible();await expect(page.getByTestId('not-found-home')).toHaveAttribute('href','/tree');await expect(page.getByTestId('not-found-kinship')).toHaveAttribute('href','/kinship');const gates=await visual(page);expect(errors).toEqual([]);await fs.promises.writeFile(path.join(out,`404-${w}-${theme}.json`),JSON.stringify({w,h,theme,gates,errors},null,2));});
for(const theme of themes)test(`F1 Zalo glyph contrast ${theme} and two-column layout`,async({page})=>{await page.setViewportSize({width:1440,height:900});await page.emulateMedia({colorScheme:theme});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('401'))errors.push(m.text())});await page.goto(base+'/login',{waitUntil:'domcontentloaded'});const button=page.getByRole('button',{name:/Đăng nhập với Zalo/i});await expect(button).toBeVisible();const proof=await button.locator('span.text-\\[\\#0068FF\\]').evaluate(el=>{const color=getComputedStyle(el).color,parse=s=>(s.match(/[\\d.]+/g)||[]).slice(0,3).map(Number),lum=c=>c.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);let fg=parse(color),n=el,bg=[255,255,255];while(n){const s=getComputedStyle(n).backgroundColor,m=s.match(/[\\d.]+/g)||[];if(m.length>=3){const a=m.length>3?+m[3]:1;bg=m.slice(0,3).map((v,i)=>+v*a+bg[i]*(1-a));if(a===1)break}n=n.parentElement}const f=lum(fg),b=lum(bg);return{color,ratio:(Math.max(f,b)+.05)/(Math.min(f,b)+.05)}});expect(proof.ratio).toBeGreaterThanOrEqual(MIN_AA);const layout=await page.evaluate(()=>{const intro=document.querySelector('[data-testid="login-intro"]'),card=document.querySelector('section > div.max-w-md');return{introWidth:intro?.getBoundingClientRect().width,cardWidth:card?.getBoundingClientRect().width}});expect(layout.introWidth).toBeGreaterThanOrEqual(960);expect(layout.cardWidth).toBeLessThanOrEqual(400);expect(errors).toEqual([]);await fs.promises.writeFile(path.join(out,`zalo-${theme}.json`),JSON.stringify({theme,proof,layout,errors},null,2));});
