const { test, expect } = require('@playwright/test');
const fs = require('node:fs'), path = require('node:path');
const MIN_AA=4.5, SMALL_WIDTHS=[390,320], HEIGHTS=[844,700], THEMES=['light','dark'], HOLD_MS=600, REDIRECT_MS=500, WAIT_MS=2000;
const base=process.env.APPLE_PHASE2_BASE;
if(!base||!/^http:\/\/127\.0\.0\.1:1[0-9]{4}$/.test(base)) throw Error('APPLE_PHASE2_BASE required (http://127.0.0.1:1xxxx)');
const out=process.env.APPLE_PHASE2_ARTIFACTS||path.resolve(__dirname,'../../.agents/tester/RESULTS/apple_phase2_email_verify_browser'); fs.mkdirSync(out,{recursive:true});
const SESSION={user:{id:'e2e',display_name:'E2E',is_demo:false,created_at:'2026-01-01T00:00:00Z'},is_new:false,conflict_detected:false};
const ERR={code:'INVALID_TOKEN',message:'Liên kết xác thực đã hết hạn hoặc không đúng định dạng.'};
let current={}; const cases=[];
const isWhitelisted=e=>e.status===401&&/\/api\/v1\/me(?:\?|$)/.test(e.url||'');
async function ctx(browser,mode='invalid',w=1440,h=900,theme='light'){const c=await browser.newContext({viewport:{width:w,height:h},locale:'vi-VN',colorScheme:theme});await c.route('**/api/**',r=>{const u=r.request().url();if(/\/me(?:\?|$)/.test(u))return r.fulfill({status:401,contentType:'application/json',body:'{"code":"UNAUTHENTICATED"}'});if(u.includes('/auth/email/verify')){if(mode==='hang')return new Promise(()=>{});if(mode==='success')return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(SESSION)});if(mode==='invalid')return r.fulfill({status:401,contentType:'application/json',body:JSON.stringify(ERR)});}return r.fulfill({status:404,contentType:'application/json',body:'{}'});});return c;}
async function start(c,url='/auth/email/verify?token=fake-token'){const p=await c.newPage(),errors=[],responses=[];p.on('pageerror',e=>errors.push({message:e.message,url:null,status:null}));p.on('response',r=>responses.push({url:r.url(),status:r.status()}));p.on('console',m=>{if(m.type()==='error'){const loc=m.location().url||null;const match=responses.find(r=>r.url===loc)||responses.find(r=>m.text().includes(r.url));errors.push({message:m.text(),url:match?.url||loc,status:match?.status??null});}});current.errors=errors;current.p=p;await p.goto(base+url,{waitUntil:'domcontentloaded'});return{p,errors};}
const sweep=`(()=>{const lum=s=>{const m=s.match(/[\\d.]+/g)||[0,0,0],a=m.slice(0,3).map(v=>+v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*a[0]+.7152*a[1]+.0722*a[2]},parse=s=>{let m=s.match(/[\\d.]+/g)||[0,0,0];return[+m[0],+m[1],+m[2],m.length>3?+m[3]:1]},out=[];for(const e of document.querySelectorAll('h1,h2,h3,p,span,a,button'))if(e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden'&&(e.innerText||'').trim()&&!e.closest('[aria-hidden=true]')){let fg=parse(getComputedStyle(e).color),bg=[255,255,255],n=e;while(n){let x=parse(getComputedStyle(n).backgroundColor);if(x[3]){bg=x.slice(0,3).map((v,i)=>v*x[3]+bg[i]*(1-x[3]));if(x[3]===1)break}n=n.parentElement}let a=lum('rgb('+fg.slice(0,3)+')'),b=lum('rgb('+bg+')');out.push({text:e.innerText.trim().slice(0,40),ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)})}return out})()`;
async function visual(p,theme,w,state){const r=await p.evaluate(sweep);expect(r.length).toBeGreaterThan(0);expect(r.filter(x=>!Number.isFinite(x.ratio)||x.ratio<MIN_AA)).toEqual([]);const o=await p.evaluate(()=>[document.documentElement,document.body].map(x=>x.scrollWidth-x.clientWidth));expect(o.every(x=>x<=0)).toBeTruthy();await p.evaluate(()=>document.activeElement?.blur());await p.keyboard.press('Tab');const f=await p.locator(':focus-visible').first().evaluate(e=>{const s=getComputedStyle(e);return s.outlineStyle!=='none'||s.boxShadow!=='none'});expect(f).toBeTruthy();(current.visual||=[]).push({theme,width:w,state,lowest:r.slice().sort((a,b)=>a.ratio-b.ratio).slice(0,3),overflow:o,focus:f});}
test.afterEach(async({},info)=>{const record={title:info.title,status:info.status,expectedStatus:info.expectedStatus,errors:current.errors||[],whitelisted:(current.errors||[]).filter(isWhitelisted),nonWhitelisted:(current.errors||[]).filter(e=>!isWhitelisted(e)),visual:current.visual||[],proof:current.proof||{}};cases.push(record);await fs.promises.writeFile(path.join(out,'case-'+info.title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.json'),JSON.stringify(record,null,2));await fs.promises.writeFile(path.join(out,'summary.json'),JSON.stringify({cases},null,2));current={};});
test('pending working status while verification request hangs',async({browser})=>{const c=await ctx(browser,'hang'),{p,errors}=await start(c);await expect(p.locator('[data-testid="verify-loading"]')).toBeVisible();await expect(p.locator('[data-testid="status-disc-working"]')).toBeVisible();current.proof={loading:true,statusDiscWorking:true};expect(errors.filter(e=>!isWhitelisted(e))).toEqual([]);await c.close();});
test('verified redirect timer frozen and end-to-end',async({browser})=>{const c=await ctx(browser,'success'),p=await c.newPage();await p.clock.pauseAt(new Date('2026-09-27T12:00:00Z'));await p.goto(base+'/auth/email/verify?token=good-token',{waitUntil:'domcontentloaded'});await expect(p.locator('[data-testid="verify-success"]')).toBeVisible();await expect(p.locator('[data-testid="status-disc-success"]')).toBeVisible();await p.waitForTimeout(HOLD_MS+100);const frozenPath=new URL(p.url()).pathname;expect(frozenPath).toBe('/auth/email/verify');current.proof={frozenPath,holdMs:HOLD_MS+100};await c.close();const fresh=await ctx(browser,'success'),q=await fresh.newPage(),started=Date.now();await q.goto(base+'/auth/email/verify?token=good-token',{waitUntil:'domcontentloaded'});await expect.poll(()=>new URL(q.url()).pathname,{timeout:WAIT_MS}).toBe('/tree');current.proof.liveRedirectPath=new URL(q.url()).pathname;current.proof.liveRedirectElapsedMs=Date.now()-started;await fresh.close();});
test('expired token displays error and retry/login actions',async({browser})=>{const c=await ctx(browser,'invalid'),{p}=await start(c,'/auth/email/verify?token=invalid-token-abc');await expect(p.locator('[data-testid="verify-error"]')).toBeVisible();await expect(p.locator('[data-testid="status-disc-error"]')).toBeVisible();await expect(p.getByRole('button',{name:'Thử lại'})).toBeVisible();await expect(p.getByRole('link',{name:'Về trang đăng nhập'})).toBeVisible();current.proof={verifyError:true,statusDiscError:true,retry:true,returnLogin:true};await c.close();});
test('missing token displays non-retryable error',async({browser})=>{const c=await ctx(browser,'none'),{p}=await start(c,'/auth/email/verify');await expect(p.locator('[data-testid="verify-error"]')).toBeVisible();await expect(p.getByRole('button',{name:'Thử lại'})).toHaveCount(0);await expect(p.getByRole('link',{name:'Về trang đăng nhập'})).toBeVisible();current.proof={verifyError:true,retry:false,returnLogin:true};await c.close();});
test('error and working responsive light/dark visual checks',async({browser})=>{for(const state of ['invalid','hang'])for(const theme of THEMES)for(let i=0;i<SMALL_WIDTHS.length;i++){const c=await ctx(browser,state,SMALL_WIDTHS[i],HEIGHTS[i],theme),{p,errors}=await start(c,state==='hang'?'/auth/email/verify?token=fake':'/auth/email/verify?token=invalid');await expect(p.locator(`[data-testid="verify-${state==='hang'?'loading':'error'}"]`)).toBeVisible();await visual(p,theme,SMALL_WIDTHS[i],state);expect(errors.filter(e=>!isWhitelisted(e))).toEqual([]);await c.close();}});
