const {test,expect}=require('@playwright/test');
const fs=require('node:fs'), path=require('node:path');
const OUT=path.resolve(__dirname,'../../.agents/tester/RESULTS'), SHOTS=path.resolve(__dirname,'../../.agents/shared/planning/apple-design-all-pages/evidence');
const base='http://localhost:3456', sizes=[[1440,900],[390,844],[320,568]], themes=['light','dark'];
fs.mkdirSync(OUT,{recursive:true});
async function ctx(browser,w,h,theme){return browser.newContext({viewport:{width:w,height:h},locale:'vi-VN',colorScheme:theme,serviceWorkers:'block'});}
async function demo(page){await page.goto(base+'/login',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Vào bản dùng thử'}).click();await expect(page).toHaveURL(/\/tree/);}
async function evidence(page,route,state,theme,w){const dir=path.join(SHOTS,route==='account'?'account':'not-found');fs.mkdirSync(dir,{recursive:true});await page.screenshot({path:path.join(dir,`${state}-${theme}-${w}.png`),fullPage:true});return page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:innerWidth}));}
for(const state of ['success','loading','error','empty']) for(const [w,h] of sizes) for(const theme of themes) test(`account ${state} ${theme} ${w}`,async({browser})=>{const c=await ctx(browser,w,h,theme),p=await c.newPage();try{if(state==='loading'){await p.route('**/api/v1/auth/me',r=>new Promise(()=>{}));await p.goto(base+'/account',{waitUntil:'domcontentloaded'});await expect(p.locator('main')).toBeVisible();}
else {await demo(p);if(state==='empty')await p.route('**/api/v1/auth/**',r=>/identit|contact/.test(r.request().url())?r.fulfill({status:200,contentType:'application/json',body:'[]'}):r.continue());if(state==='error')await p.route('**/api/v1/auth/**',r=>/unlink|contact/.test(r.request().url())?r.fulfill({status:500,contentType:'application/json',body:'{}'}):r.continue());await p.goto(base+'/account',{waitUntil:'domcontentloaded'});await expect(p.getByTestId('user-display-name')).toBeVisible();await expect(p.getByTestId('demo-badge')).toContainText('Phiên demo');await expect(p.getByText(/Tài khoản trải nghiệm/)).toBeVisible();await expect(p.getByText(/Liên kết với/)).toHaveCount(0);if(state==='empty')await expect(p.getByText(/Chưa có điểm liên hệ nào được lưu/)).toBeVisible();}
const m=await evidence(p,'account',state,theme,w);expect(m.scrollWidth).toBeLessThanOrEqual(w);}finally{await c.close()}});
for(const [w,h] of sizes)for(const theme of themes)test(`404 ${theme} ${w}`,async({browser})=>{const c=await ctx(browser,w,h,theme),p=await c.newPage();try{await p.goto(base+'/khong-ton-tai-xyz',{waitUntil:'domcontentloaded'});await expect(p.getByTestId('not-found')).toBeVisible();await expect(p.getByText('Đường dẫn không tồn tại')).toBeVisible();await expect(p.getByRole('heading',{name:'Không tìm thấy trang'})).toBeVisible();await expect(p.getByTestId('not-found-home')).toHaveAttribute('href','/tree');await expect(p.getByTestId('not-found-kinship')).toHaveAttribute('href','/kinship');const m=await evidence(p,'404','success',theme,w);expect(m.scrollWidth).toBeLessThanOrEqual(w);}finally{await c.close()}});
for(const w of [1440,390,320])test(`account anonymous redirect light ${w}`,async({browser})=>{const c=await ctx(browser,w,844,'light'),p=await c.newPage();try{await p.goto(base+'/account',{waitUntil:'domcontentloaded'});await expect(p).toHaveURL(/\/login\?redirect=\/account/);await expect(p.getByRole('heading',{name:'Cây Gia Phả'})).toBeVisible();}finally{await c.close()}});
for(const theme of themes)for(const route of ['/login','/tree','/account'])test(`cold first paint ${theme} ${route}`,async({browser})=>{const c=await ctx(browser,1440,900,theme),p=await c.newPage();try{if(route!='/login')await demo(p);await p.goto(base+route,{waitUntil:'domcontentloaded'});const paint=await p.evaluate(()=>({bg:getComputedStyle(document.documentElement).backgroundColor,dark:matchMedia('(prefers-color-scheme: dark)').matches}));expect(paint.dark).toBe(theme==='dark');}finally{await c.close()}});
test('theme lifecycle live switch reload storage toggle',async({browser})=>{const c=await ctx(browser,1440,900,'light'),p=await c.newPage();try{await demo(p);await p.goto(base+'/tree',{waitUntil:'domcontentloaded'});const bg=()=>p.evaluate(()=>getComputedStyle(document.documentElement).backgroundColor);const light=await bg();await p.emulateMedia({colorScheme:'dark'});await p.waitForTimeout(100);const dark=await bg();expect(dark).not.toBe(light);await p.emulateMedia({colorScheme:'light'});expect(await bg()).toBe(light);await p.emulateMedia({colorScheme:'dark'});await p.reload();expect(await p.evaluate(()=>matchMedia('(prefers-color-scheme: dark)').matches)).toBe(true);const d=await p.evaluate(()=>({keys:Object.keys(localStorage),toggles:[...document.querySelectorAll('button,[role=switch]')].filter(x=>/theme|dark mode|giao diện/i.test(x.innerText+' '+x.getAttribute('aria-label'))).length}));expect(d.keys.filter(k=>/theme/i.test(k))).toEqual([]);expect(d.toggles).toBe(0);}finally{await c.close()}});

for(const route of ['/tree','/feed'])for(const w of [390,320])test(`mobile ergonomics ${route} ${w}`,async({browser})=>{const c=await ctx(browser,w,844,'light'),p=await c.newPage();try{await demo(p);await p.goto(base+route,{waitUntil:'domcontentloaded'});const m=await p.evaluate(()=>{const nav=document.querySelector('nav[aria-label="Điều hướng di động"]');return{scrollWidth:document.documentElement.scrollWidth,items:[...(nav?.querySelectorAll('a,button')||[])].map(e=>{const r=e.getBoundingClientRect();return{width:r.width,height:r.height,right:r.right}}),compass:[...document.querySelectorAll('[aria-label*=compass i]')].map(e=>e.getBoundingClientRect().right)}});expect(m.scrollWidth).toBeLessThanOrEqual(w);expect(m.items.length).toBeGreaterThan(0);for(const x of m.items){expect(x.width).toBeGreaterThanOrEqual(78);expect(x.height).toBeGreaterThanOrEqual(60);expect(x.right).toBeLessThanOrEqual(w);}expect(m.compass.every(x=>x<=w)).toBe(true);}finally{await c.close()}});
