const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const BASE = process.env.APPLE_PHASE4M1_BASE || 'http://127.0.0.1:14180';
const OUT = process.env.APPLE_PHASE4M1_ARTIFACTS || path.resolve(__dirname, '../../.agents/tester/RESULTS/apple_phase4_m1_journey');
fs.mkdirSync(OUT, { recursive: true });
async function contrast(locator) { return locator.evaluate(el => { const rgb=s=>(s.match(/[\d.]+/g)||[]).slice(0,3).map(Number), L=a=>{const x=a.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4});return .2126*x[0]+.7152*x[1]+.0722*x[2]};const f=L(rgb(getComputedStyle(el).color));let n=el,bg=[255,255,255];while(n){const s=getComputedStyle(n).backgroundColor;if(!s.includes('0, 0, 0, 0')){bg=rgb(s);if(!s.startsWith('rgba'))break}n=n.parentElement}const b=L(bg);return +((Math.max(f,b)+.05)/(Math.min(f,b)+.05)).toFixed(3); }); }
async function demoContext(browser, theme = 'light') {
  const ctx = await browser.newContext({ colorScheme: theme, viewport: { width: 1440, height: 900 }, locale: 'vi-VN' });
  const origin = new URL(BASE).origin;
  const response = await ctx.request.post(BASE + '/api/v1/auth/demo', { headers: { Origin: origin }, data: '' });
  if (!response.ok()) throw new Error(`demo login failed: POST /api/v1/auth/demo → ${response.status()} (check proxy Origin rewrite)`);
  return ctx;
}
async function resolveMember(page) { const fr=await page.request.get(BASE+'/api/v1/families');expect(fr.ok()).toBeTruthy();const families=(await fr.json()).families;const mr=await page.request.get(BASE+'/api/v1/members');expect(mr.ok()).toBeTruthy();const body=await mr.json(),members=Array.isArray(body)?body:(body.members||[]);let member=members.find(m=>m.full_name==='Nguyễn Văn An');if(member)return {member,families};for(const family of families){const r=await page.request.get(`${BASE}/api/v1/families/${family.id}/tree`);const tree=await r.json();const walk=nodes=>{for(const node of nodes||[]){if(node.full_name==='Nguyễn Văn An')return node;const found=walk(node.children);if(found)return found;}};member=walk(tree.roots);if(member)return {member:{...member,family_id:family.id},families};}throw new Error('Root Nguyễn Văn An not found through members API or family tree roots'); }
test('M1 live setup resolves root member Nguyễn Văn An and family id via API',async({page})=>{const {member}=await resolveMember(page);expect(member.id).toBeTruthy();expect(member.family_id).toBeTruthy();});
test('M1 desktop placement @1440: breadcrumb and desktop CTA link targets',async({browser})=>{const ctx=await demoContext(browser);const page=await ctx.newPage();const {member}=await resolveMember(page);await page.setViewportSize({width:1440,height:900});await page.goto(`${BASE}/members/${member.id}`);const crumb=page.getByTestId('member-tree-breadcrumb'),desktop=page.getByTestId('member-view-tree'),mobile=page.getByTestId('member-view-tree-mobile');await expect(crumb).toBeVisible();await expect(crumb).toContainText('← Gia phả');await expect(crumb).toHaveAttribute('href','/tree');await expect(desktop).toBeVisible();await expect(desktop).toHaveAttribute('href',`/tree?family=${member.family_id}`);await expect(mobile).toBeHidden();await ctx.close();});
test('M1 responsive placement @390 inverted and @320 no horizontal overflow',async({browser})=>{const ctx=await demoContext(browser);const page=await ctx.newPage();const {member}=await resolveMember(page);await page.goto(`${BASE}/members/${member.id}`);const desktop=page.getByTestId('member-view-tree'),mobile=page.getByTestId('member-view-tree-mobile');await page.setViewportSize({width:390,height:844});await expect(mobile).toBeVisible();await expect(desktop).toBeHidden();await page.setViewportSize({width:320,height:800});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(321);await ctx.close();});
test('M1 breadcrumb and desktop/mobile CTA contrast ≥4.5 in light and dark',async({browser})=>{const rows=[];for(const theme of ['light','dark']){const context=await demoContext(browser,theme),page=await context.newPage(),{member}=await resolveMember(page);await page.goto(`${BASE}/members/${member.id}`);const crumb=page.getByTestId('member-tree-breadcrumb'),desktop=page.getByTestId('member-view-tree'),mobile=page.getByTestId('member-view-tree-mobile');for(const [name,el] of [['breadcrumb',crumb],['desktop CTA',desktop]]){const value=await contrast(el);rows.push({theme,name,ratio:value});fs.writeFileSync(path.join(OUT,'contrast.json'),JSON.stringify(rows,null,2));expect(value,`${theme} ${name}`).toBeGreaterThanOrEqual(4.5);}await page.setViewportSize({width:390,height:844});const value=await contrast(mobile);rows.push({theme,name:'mobile CTA',ratio:value});fs.writeFileSync(path.join(OUT,'contrast.json'),JSON.stringify(rows,null,2));expect(value,`${theme} mobile CTA`).toBeGreaterThanOrEqual(4.5);await context.close();}fs.writeFileSync(path.join(OUT,'contrast.json'),JSON.stringify(rows,null,2));});
test('M1 live click-through: detail → family-selected tree payload → plain breadcrumb fallback',async({browser})=>{const ctx=await demoContext(browser);const page=await ctx.newPage();const {member,families}=await resolveMember(page);await page.setViewportSize({width:1440,height:900});await page.goto(`${BASE}/members/${member.id}`);await page.getByTestId('member-view-tree').click();await expect(page).toHaveURL(new RegExp(`/tree\\?family=${member.family_id}$`));await expect(page.locator('select').first()).toHaveValue(member.family_id);await expect(page.getByTestId('tree-family-name')).toHaveText(families.find(f=>f.id===member.family_id).name);const payload=await page.request.get(`${BASE}/api/v1/families/${member.family_id}/tree`);expect((await payload.json()).family_id).toBe(member.family_id);await page.getByTestId('member-tree-breadcrumb').click();await expect(page).toHaveURL(/\/tree$/);await expect(page.getByTestId('tree-family-name')).toHaveText(families[0].name);await expect(page.locator('select').first()).toHaveValue(families[0].id);await page.screenshot({path:path.join(OUT,'journey.png')});await ctx.close();});
