const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const OUT=path.resolve(__dirname,'../../.agents/tester/RESULTS'),SHOTS=path.resolve(__dirname,'../../.agents/shared/planning/apple-design-all-pages/evidence');
const base='http://localhost:3456',sizes=[[1440,900],[390,844],[320,568]],themes=['light','dark'];
const fsDir=(p)=>fs.mkdirSync(p,{recursive:true});fsDir(OUT);
async function ctx(browser,w,h,t){return browser.newContext({viewport:{width:w,height:h},locale:'vi-VN',colorScheme:t,serviceWorkers:'block'});}
async function demo(p){await p.goto(base+'/login',{waitUntil:'domcontentloaded'});await p.locator('[data-testid="demo-login-btn"]').click();await expect(p).toHaveURL(/\/tree/);}
const visual=async(p,route,state,t,w)=>p.evaluate(({route,state,t,w})=>{const rgb=s=>{const m=s.match(/[\d.]+/g)||[];return m.slice(0,3).map(Number)};const lum=c=>c.map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4}).reduce((a,x,i)=>a+x*[.2126,.7152,.0722][i],0);const contrast=(a,b)=>{a=lum(a);b=lum(b);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05)};const els=[...document.querySelectorAll('h1,h2,h3,p,button,a,[data-testid="demo-badge"]')].filter(e=>e.getClientRects().length&&!e.closest('[aria-hidden=true]'));const rows=els.map(e=>{const s=getComputedStyle(e),f=rgb(s.color);let n=e,bg=[255,255,255];while(n){const q=getComputedStyle(n).backgroundColor;if(q!=='rgba(0, 0, 0, 0)'){bg=rgb(q);break}n=n.parentElement}return{text:(e.innerText||'').trim().slice(0,30),ratio:+contrast(f,bg).toFixed(2),size:parseFloat(s.fontSize),lh:parseFloat(s.lineHeight),tag:e.tagName,selector:e.getAttribute('data-testid')||e.tagName.toLowerCase()}});const head=rows.find(x=>/^H[1-3]$/.test(x.tag)),body=rows.find(x=>x.tag==='P'&&x.text);return{scrollWidth:document.documentElement.scrollWidth,clientWidth:innerWidth,contrast:rows.filter(x=>x.text).map(x=>({...x,pass:x.ratio>=(x.size>=24?3:4.5)}),).filter(x=>!x.pass).slice(0,8),minRatio:Math.min(...rows.filter(x=>x.text).map(x=>x.ratio)),heading:head&&{text:head.text,lineHeight:head.lh/fontSizeOf(head),selector:head.selector},body:body&&{text:body.text,lineHeight:body.lh/fontSizeOf(body),selector:body.selector},route,state,t,w};function fontSizeOf(r){const e=els.find(x=>(x.getAttribute('data-testid')||x.tagName.toLowerCase())===r.selector);return parseFloat(getComputedStyle(e).fontSize)}}, {route,state,t,w});
async function capture(p,r,s,t,w){const dir=path.join(SHOTS,r==='account'?'account':'not-found');fsDir(dir);await p.screenshot({path:path.join(dir,`${s}-${t}-${w}.png`),fullPage:true});}
async function checks(p,r,s,t,w){const d=await visual(p,r,s,t,w);expect(d.scrollWidth).toBeLessThanOrEqual(w);expect(d.heading?.lineHeight??0).toBeGreaterThanOrEqual(1.45);expect(d.body?.lineHeight??0).toBeGreaterThanOrEqual(1.6);await p.evaluate(()=>document.activeElement.blur());await p.keyboard.press('Tab');const ring=await p.locator(':focus-visible').first().evaluate(e=>{const x=getComputedStyle(e);return x.outlineStyle!=='none'||x.boxShadow!=='none'});expect(ring).toBeTruthy();return{...d,focus:ring};}
for(const state of ['success','loading','error','empty'])for(const [w,h]of sizes)for(const t of themes)test(`account ${state} ${t} ${w}`,async({browser})=>{const c=await ctx(browser,w,h,t),p=await c.newPage();try{if(state==='loading'){await p.route('**/api/v1/auth/me',()=>new Promise(()=>{}));await p.goto(base+'/account',{waitUntil:'domcontentloaded'});await expect(p.locator('main')).toBeVisible();}else{await demo(p);if(state==='empty')await p.route('**/api/v1/auth/**',r=>/identit|contact/.test(r.request().url())?r.fulfill({status:200,contentType:'application/json',body:'[]'}):r.continue());if(state==='error')await p.route('**/api/v1/auth/**',r=>/unlink|contact/.test(r.request().url())?r.fulfill({status:500,contentType:'application/json',body:'{}'}):r.continue());await p.goto(base+'/account',{waitUntil:'domcontentloaded'});await expect(p.getByTestId('user-display-name')).toBeVisible();await expect(p.getByTestId('demo-badge')).toContainText('Phiên demo');await expect(p.getByText(/Tài khoản trải nghiệm/)).toBeVisible();await expect(p.getByText(/Liên kết với/)).toHaveCount(0);if(state==='empty')await expect(p.getByText(/Chưa có điểm liên hệ nào được lưu/)).toBeVisible();}const proof=await checks(p,'account',state,t,w);await capture(p,'account',state,t,w);fs.appendFileSync(path.join(OUT,'m4-visual-proof.jsonl'),JSON.stringify({route:'/account',state,theme:t,viewport:w,...proof,staged:['error','empty','loading'].includes(state)})+'\n');}finally{await c.close()}});
for(const [w,h]of sizes)for(const t of themes)test(`404 ${t} ${w}`,async({browser})=>{const c=await ctx(browser,w,h,t),p=await c.newPage();try{await p.goto(base+'/khong-ton-tai-xyz',{waitUntil:'domcontentloaded'});await expect(p.getByTestId('not-found')).toBeVisible();await expect(p.getByRole('heading',{name:'Không tìm thấy trang'})).toBeVisible();await expect(p.getByTestId('not-found-home')).toHaveAttribute('href','/tree');await expect(p.getByTestId('not-found-kinship')).toHaveAttribute('href','/kinship');const proof=await checks(p,'404','success',t,w);await capture(p,'404','success',t,w);fs.appendFileSync(path.join(OUT,'m4-visual-proof.jsonl'),JSON.stringify({route:'/404',state:'success',theme:t,viewport:w,...proof,staged:false})+'\n');}finally{await c.close()}});
for(const w of [1440,390,320])test(`guard ${w}`,async({browser})=>{const c=await ctx(browser,w,844,'light'),p=await c.newPage();try{await p.goto(base+'/account',{waitUntil:'domcontentloaded'});await expect(p).toHaveURL(/\/login\?redirect=\/account/);const proof=await checks(p,'guard','anonymous','light',w);fs.appendFileSync(path.join(OUT,'m4-visual-proof.jsonl'),JSON.stringify({route:'/account',state:'guard',theme:'light',viewport:w,...proof,staged:false})+'\n');}finally{await c.close()}});
for(const t of themes)test(`cold login paint ${t}`,async({browser})=>{const c=await ctx(browser,1440,900,t),p=await c.newPage();try{await p.goto(base+'/login',{waitUntil:'domcontentloaded'});const d=await p.evaluate(()=>({html:getComputedStyle(document.documentElement).backgroundColor,body:getComputedStyle(document.body).backgroundColor}));if(t==='dark'){expect(d.html).not.toBe('rgb(255, 255, 255)');expect(d.body).not.toBe('rgb(255, 255, 255)');}else{expect(d.html).toMatch(/rgb\(/);expect(d.body).toMatch(/rgb\(/);}console.log('COLDPAINT|'+t+'|'+JSON.stringify(d));}finally{await c.close()}});
for(const route of ['/tree','/feed'])for(const w of [390,320])test(`mobile ergonomics ${route} ${w}`,async({browser})=>{const c=await ctx(browser,w,844,'light'),p=await c.newPage();try{await demo(p);await p.goto(base+route,{waitUntil:'domcontentloaded'});const d=await p.evaluate(()=>{const n=document.querySelector('nav[aria-label="Điều hướng di động"]');return{scrollWidth:document.documentElement.scrollWidth,items:[...(n?.querySelectorAll('a,button')||[])].map(e=>{const r=e.getBoundingClientRect();return{width:r.width,height:r.height,right:r.right}})}});expect(d.scrollWidth).toBeLessThanOrEqual(w);for(const x of d.items){expect(x.width).toBeGreaterThanOrEqual(78);expect(x.height).toBeGreaterThanOrEqual(60);expect(x.right).toBeLessThanOrEqual(w);}}finally{await c.close()}});
for(const w of [390,320])test(`member ergonomics ${w}`,async({browser})=>{const c=await ctx(browser,w,844,'light'),p=await c.newPage();try{await demo(p);const families=await c.request.get(base+'/api/v1/families');const fams=(await families.json()).families||[];const members=await c.request.get(base+'/api/v1/members?limit=200');const items=(await members.json()).items||[];const root=items.find(x=>x.family_id===fams[0]?.id&&x.generation_index===1)||items[0];const id=root&&'/members/'+root.id;expect(id).toBeTruthy();await p.goto(base+id,{waitUntil:'domcontentloaded'});const d=await p.evaluate(()=>{const n=document.querySelector('nav[aria-label="Điều hướng di động"]');return{scrollWidth:document.documentElement.scrollWidth,items:[...(n?.querySelectorAll('a,button')||[])].map(e=>{const r=e.getBoundingClientRect();return{width:r.width,height:r.height,right:r.right}})}});expect(d.scrollWidth).toBeLessThanOrEqual(w);for(const x of d.items){expect(x.width).toBeGreaterThanOrEqual(78);expect(x.height).toBeGreaterThanOrEqual(60);expect(x.right).toBeLessThanOrEqual(w);}}finally{await c.close()}});
