const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const BASE = process.env.APPLE_PHASE4TC_BASE || 'http://127.0.0.1:14180';
const OUT = process.env.APPLE_PHASE4TC_ARTIFACTS || path.resolve(__dirname, '../../.agents/tester/RESULTS/apple_phase4_tree_chrome');
fs.mkdirSync(OUT, { recursive: true });
const DEMO = 'http://localhost:3456';
const contrast = el => el.evaluate(e => { const rgb=s=>{const m=s.match(/[\d.]+/g)||[];return m.slice(0,3).map(Number)};const L=a=>{const x=a.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4});return .2126*x[0]+.7152*x[1]+.0722*x[2]};const fg=L(rgb(getComputedStyle(e).color));let n=e,bg=[255,255,255];while(n){const c=getComputedStyle(n).backgroundColor;if(!c.includes('0, 0, 0, 0')){bg=rgb(c);if(!c.startsWith('rgba')||Number(c.match(/,\s*([\d.]+)\)$/)?.[1]||1)===1)break}n=n.parentElement}const b=L(bg);return +((Math.max(fg,b)+.05)/(Math.min(fg,b)+.05)).toFixed(2)});
const stage = mode => async route => { const u=new URL(route.request().url()); if(u.pathname==='/api/v1/me')return route.fulfill({status:401,body:'{}'}); if(u.pathname==='/api/v1/families')return route.fulfill({json:{families:[{id:'fam-a',name:'Gia đình 1'},{id:'fam-b',name:'Gia đình 2'}]}});const m=u.pathname.match(/families\/([^/]+)\/tree/);if(m){if(mode==='loading'){await new Promise(r=>setTimeout(r,8000));return route.fulfill({json:{family_id:m[1],roots:[]}})}if(mode==='error')return route.fulfill({status:500,json:{message:'Lỗi thử nghiệm'}});return route.fulfill({json:{family_id:m[1],generations:[{index:1,label:'Đời thứ 1',count:mode==='empty'?0:12}],roots:mode==='empty'?[]:[{id:'node-1',full_name:'Nguyễn Văn An',gender:'male',generation_index:1,is_living:true,spouse_ids:[],children:[]}]}})}return route.continue()};
async function tree(page,mode){await page.route('**/api/**',stage(mode));await page.goto(BASE+'/tree')}
test('independent tree chrome 4-state × 2-theme × 3-viewport matrix',async({browser})=>{const rows=[],states=['success','loading','error','empty'];for(const state of states)for(const theme of ['light','dark'])for(const [w,h] of [[1440,900],[390,844],[320,800]]){const c=await browser.newContext({viewport:{width:w,height:h},colorScheme:theme});const p=await c.newPage(),errs=[],warn=[];p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text());if(m.type()==='warning')warn.push(m.text())});await tree(p,state);const sel=state==='loading'?'tree-loading':state==='error'?'tree-retry':state==='empty'?'tree-empty-state':'tree-family-name';await expect(p.getByTestId(sel).or(p.locator('.'+sel))).toBeVisible({timeout:state==='loading'?5000:15000});if(state==='error')await p.getByTestId('tree-retry').click();if(state==='empty'){await expect(p.getByTestId('tree-add-auth-hint')).toBeVisible();await expect(p.getByTestId('empty-add-member')).toHaveCount(0)}const data=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,width:innerWidth}));const candidates=await p.locator('h1,button,a,[role=status],p').evaluateAll(es=>es.filter(e=>e.getClientRects().length&&e.innerText.trim()));const ratios=[];for(const e of candidates)ratios.push(await contrast(p.locator('xpath=//html').locator(':scope')) .catch(()=>0));const min=ratios.length?Math.min(...ratios):99;const focus=[];for(const id of ['zoom-in','zoom-out','compass-center','tree-retry']){const x=p.getByTestId(id);if(await x.count()&&await x.isVisible()){await x.focus();focus.push(await x.evaluate(e=>{const s=getComputedStyle(e);return (s.outlineStyle!=='none'&&s.outlineColor!=='transparent')||s.boxShadow!=='none'}))}}if(state==='success')await p.screenshot({path:path.join(OUT,`success-${w}-${theme}.png`)});const row={state,w,h,theme,...data,ratios:min,focus,errors:errs,warnings:warn};rows.push(row);if(errs.length)await p.screenshot({path:path.join(OUT,`failure-${state}-${w}-${theme}.png`)});await c.close()}fs.writeFileSync(path.join(OUT,'summary.json'),JSON.stringify(rows,null,2));expect(rows.every(r=>!r.overflow&&r.errors.length===0)).toBeTruthy();});
test('live family preselect, demo notice and tree invariants',async({page})=>{const families=await page.request.get(BASE+'/api/v1/families');expect(families.ok()).toBeTruthy();const fs0=(await families.json()).families;expect(fs0.length).toBeGreaterThan(1);for(const f of [fs0[1],fs0[0]]){await page.goto(BASE+'/tree'+(f===fs0[0]?'':`?family=${f.id}`));await expect(page.getByTestId('tree-family-name')).toHaveText(f.name);await expect.poll(async()=>{const r=await page.request.get(BASE+`/api/v1/families/${f.id}/tree`);return (await r.json()).family_id}).toBe(f.id)}await page.goto(BASE+'/tree?family=bogus');await expect(page.getByTestId('tree-family-name')).toHaveText(fs0[0].name);const login=await page.request.post(BASE+'/api/v1/auth/demo',{headers:{Origin:DEMO},data:''});expect(login.ok()).toBeTruthy();await page.goto(BASE+'/tree');await expect(page.getByTestId('tree-demo-notice')).toContainText('Phiên Demo');const canvas=page.locator('canvas');await expect(canvas).toHaveCount(1);await expect(page.getByTestId('zoom-in')).toBeVisible();await page.getByTestId('zoom-in').click();await page.getByTestId('zoom-out').click();await page.getByTestId('compass-center').click();});
test('rendered card contrast measurement only',async({browser})=>{for(const colorScheme of ['light','dark']){const c=await browser.newContext({colorScheme}),p=await c.newPage();await p.goto(BASE+'/tree');await expect(p.locator('canvas')).toHaveCount(1);const cards=p.locator('[data-testid^="tree-node"]');const n=await cards.count();const measures=[];for(let i=0;i<Math.min(n,10);i++){const el=cards.nth(i);measures.push({text:(await el.innerText()).slice(0,60),contrast:await contrast(el)})}console.log('MEASUREMENT:',JSON.stringify({colorScheme,count:measures.length,min:Math.min(...measures.map(x=>x.contrast)),avg:measures.reduce((a,x)=>a+x.contrast,0)/(measures.length||1),examples:measures}));await c.close()}});
