const { test, expect } = require('@playwright/test');
const BASE=process.env.TREE_VISUAL_BASE||'http://127.0.0.1:14180';
async function login(browser,theme,width,height){const c=await browser.newContext({colorScheme:theme,viewport:{width,height},locale:'vi-VN',serviceWorkers:'block'});const r=await c.request.post(BASE+'/api/v1/auth/demo',{headers:{Origin:new URL(BASE).origin},data:''});if(!r.ok())throw Error(`demo auth ${r.status()}`);return c}
async function ready(p){await p.goto(BASE+'/tree');await expect(p.locator('[data-testid="tree-world"]')).toHaveCount(1,{timeout:10000});await expect(p.locator('button[aria-label*="Đời thứ"]').first()).toBeVisible({timeout:10000})}
async function settle(p){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))}
async function transform(p){return p.locator('[data-testid="tree-world"]').evaluate(e=>e.style.transform)}
test('supplemental tree visual contract: six viewport/theme cells, fit/reflow, contrast, canvas and hygiene',async({browser})=>{
 const failures=[],cells=[];
 for(const theme of ['light','dark'])for(const [w,h] of [[1440,900],[390,844],[320,800]]){const c=await login(browser,theme,w,h);try{const p=await c.newPage(), pageErrors=[],consoleErrors=[],server=[];p.on('pageerror',e=>pageErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});p.on('response',r=>{if(r.status()>=500)server.push({url:r.url(),status:r.status()})});await ready(p);const world=p.locator('[data-testid="tree-world"]'),canvas=world.locator('canvas');const initial=await p.evaluate(()=>({buttons:document.querySelectorAll('.tree-viewport button').length,dpr:devicePixelRatio,canvas:[...document.querySelectorAll('[data-testid="tree-world"] canvas')].map(x=>[x.width,x.height]),vp:document.querySelector('.tree-viewport').getBoundingClientRect().toJSON(),nav:(()=>{const n=document.querySelector('nav[aria-label="Điều hướng di động"]');return n&&getComputedStyle(n).display!=='none'?n.getBoundingClientRect().top:null})()}));expect(initial.buttons).toBeLessThanOrEqual(300);expect(initial.dpr).toBeLessThanOrEqual(2);expect(await canvas.count()).toBe(1);if(initial.nav!==null)expect(initial.vp.bottom).toBeLessThanOrEqual(initial.nav+1);
 const card=p.locator('.tree-viewport button[aria-label*="Đời thứ"]').first();const name=await card.evaluate(e=>{const r=document.createRange();r.selectNodeContents(e);return r.toString().trim().split('Đời thứ')[0].trim()});expect(name.length,`${theme}/${w} accessible visible node name`).toBeGreaterThan(1);await expect(card).toBeVisible();
 const image=await p.screenshot();const fg=await card.evaluate(e=>getComputedStyle(e).color);
 // Pixel contrast is sampled from the card's rendered screenshot using browser canvas decoding.
 const contrast=await p.evaluate(async({encoded,selector})=>{const b=Uint8Array.from(atob(encoded),x=>x.charCodeAt(0)),im=await createImageBitmap(new Blob([b],{type:'image/png'})),c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d');x.drawImage(im,0,0);const e=document.querySelector(selector),r=e.getBoundingClientRect(),fg=getComputedStyle(e).color.match(/\d+/g).slice(0,3).map(Number),pts=[[r.left+5,r.top+5],[r.right-5,r.bottom-5]].filter(([a,d])=>a>=0&&d>=0&&a<innerWidth&&d<innerHeight);const L=a=>a.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0),f=L(fg);return pts.map(([a,d])=>{const bg=[...x.getImageData(Math.round(a),Math.round(d),1,1).data].slice(0,3),q=L(bg);return(fg,bg,(Math.max(f,q)+.05)/(Math.min(f,q)+.05))})},{encoded:image.toString('base64'),selector:'.tree-viewport button[aria-label*="Đời thứ"]'});expect(contrast.length).toBeGreaterThan(0);expect(Math.min(...contrast)).toBeGreaterThanOrEqual(4.5);
 const pointer=[];await p.evaluate(()=>{window.__captures=[];const f=Element.prototype.setPointerCapture;Element.prototype.setPointerCapture=function(id){window.__captures.push(this.tagName+'.'+this.className);return f.call(this,id)}});await p.getByTestId('zoom-in').click();const zoom=await transform(p);await p.getByTestId('compass-east').click();const pan=await transform(p);expect(pan).not.toBe(zoom);await p.getByTestId('fit-view').click();await settle(p);expect(await p.locator('[data-testid="tree-world"] canvas').count()).toBe(1);expect(await p.evaluate(()=>window.__captures)).toEqual([]);
 const cell={theme,width:w,height:h,initial,contrast,errors:{pageErrors,consoleErrors,server}};cells.push(cell);expect(pageErrors).toEqual([]);expect(consoleErrors).toEqual([]);expect(server).toEqual([]); }finally{await c.close()}}
});
test('orientation connector geometry transposes; pan and minimap viewport rect follows zoom',async({browser})=>{const c=await login(browser,'light',1440,900);try{const p=await c.newPage();await ready(p);const bands=p.locator('[data-testid^="band-gen-"]');await expect(bands.first()).toBeVisible();const v=await bands.first().boundingBox();await p.getByTestId('orientation-horizontal').click();await expect(p.getByTestId('orientation-horizontal')).toHaveAttribute('aria-pressed','true');await settle(p);const h=await bands.first().boundingBox();expect(Math.abs(v.y-h.y)+Math.abs(v.x-h.x)).toBeGreaterThan(1);const map=p.getByTestId('minimap-map'),rect=p.getByTestId('minimap-viewport-rect'),before=await rect.boundingBox();await p.getByTestId('zoom-in').click();await expect.poll(async()=>JSON.stringify(await rect.boundingBox())).not.toBe(JSON.stringify(before));const t=await transform(p);await p.mouse.move(700,450);await p.mouse.down();await p.mouse.move(740,480);await p.mouse.up();expect(await transform(p)).not.toBe(t);await map.focus();await p.keyboard.press('ArrowRight');}finally{await c.close()}});
test('generation rail depth, active selection and mobile rail behavior',async({browser})=>{for(const width of [1440,390,320]){const c=await login(browser,'light',width,844);try{const p=await c.newPage();await ready(p);const rail=p.getByTestId('generation-rail'),buttons=rail.locator('button');await expect(rail).toBeVisible();expect(await buttons.count()).toBeGreaterThanOrEqual(6);const last=buttons.last();await last.click();await expect(last).toHaveAttribute('aria-current','true');if(width<=767){const mode=await rail.evaluate(e=>({scrollWidth:e.scrollWidth,clientWidth:e.clientWidth,overflow:getComputedStyle(e).overflowX,display:getComputedStyle(e).display}));expect(mode.display).not.toBe('none');expect(mode.scrollWidth>=mode.clientWidth||mode.overflow==='auto'||mode.overflow==='scroll').toBeTruthy();}}finally{await c.close()}}});
