const {test,expect}=require('@playwright/test');
const BASE=process.env.TREE_RACE_BASE||'http://127.0.0.1:14180';
const A='22222222-2222-4222-8222-222222220002',B='33333333-3333-4333-8333-333333330003';
async function login(browser){const c=await browser.newContext({viewport:{width:1440,height:900},locale:'vi-VN',serviceWorkers:'block'});const r=await c.request.post(BASE+'/api/v1/auth/demo',{headers:{Origin:new URL(BASE).origin},data:''});if(!r.ok())throw Error(`demo auth ${r.status()}`);for(const id of [A,B]){const check=await c.request.get(`${BASE}/api/v1/families/${id}/tree`,{headers:{Origin:new URL(BASE).origin}});if(!check.ok())throw Error(`required seeded family unavailable: ${id} (HTTP ${check.status()})`)}return c}
async function treeRequests(page){const calls=[];page.on('request',r=>{if(new URL(r.url()).pathname.match(/\/families\/[^/]+\/tree$/))calls.push(new URL(r.url()).pathname)});return calls}
async function goTree(page,url='/tree'){await page.goto(BASE+url);await expect(page.locator('[data-testid="tree-world"]')).toHaveCount(1,{timeout:15000})}
test('latest family fetch wins and stale response cannot release newer spinner',async({browser})=>{const c=await login(browser);try{const p=await c.newPage(),calls=await treeRequests(p),holdA=()=>{};let release;const gate=new Promise(r=>release=r);await p.route(`**/api/v1/families/${A}/tree`,async route=>{holdA();await gate;await route.continue()});await goTree(p,`/tree?family=${A}`);await expect.poll(()=>calls.filter(x=>x.endsWith(`/${A}/tree`)).length).toBe(1);await p.evaluate(id=>history.replaceState({},'',`/tree?family=${id}`),B);await p.evaluate(()=>dispatchEvent(new PopStateEvent('popstate')));await expect.poll(()=>calls.filter(x=>x.endsWith(`/${B}/tree`)).length).toBe(1);await expect(p.locator('select').first()).toHaveValue(B);await expect(p.locator('[data-testid="tree-world"]')).toBeVisible();release();await expect.poll(()=>p.locator('[data-testid="tree-world"]').getAttribute('data-family-id')).not.toBe(A);await expect(p.locator('select').first()).toHaveValue(B);expect(calls.filter(x=>x.endsWith(`/${A}/tree`))).toHaveLength(1);expect(calls.filter(x=>x.endsWith(`/${B}/tree`))).toHaveLength(1); }finally{await c.close()}});
test('invalidate supersedes an older fetch and owns loading until its response settles',async({browser})=>{const c=await login(browser);try{const p=await c.newPage(),calls=await treeRequests(p);let releaseA;const gateA=new Promise(r=>releaseA=r);let releaseInvalidate;const gateI=new Promise(r=>releaseInvalidate=r);let count=0;await p.route(`**/api/v1/families/${A}/tree`,async route=>{if(++count===1){await gateA;await route.continue()}else{await gateI;await route.continue()}});await goTree(p,`/tree?family=${A}`);await expect.poll(()=>count).toBe(1);await p.evaluate(async()=>{const {useTreeStore}=await import('/src/stores/tree.ts');window.__treeStore=useTreeStore()});const invalid=p.evaluate(()=>window.__treeStore.invalidate());await expect.poll(()=>count).toBe(2);releaseA();await expect(p.locator('[data-testid="tree-world"]')).toBeVisible();expect(await p.evaluate(()=>window.__treeStore.loading)).toBe(true);releaseInvalidate();await invalid;expect(await p.evaluate(()=>window.__treeStore.loading)).toBe(false);expect(calls.filter(x=>x.endsWith(`/${A}/tree`))).toHaveLength(2)}finally{await c.close()}});
test('reset during hanging request prevents late response from repopulating store',async({browser})=>{const c=await login(browser);try{const p=await c.newPage();let release;const gate=new Promise(r=>release=r);await p.route(`**/api/v1/families/${A}/tree`,async route=>{await gate;await route.continue()});await goTree(p,`/tree?family=${A}`);await p.evaluate(async()=>{const {useTreeStore}=await import('/src/stores/tree.ts');window.__treeStore=useTreeStore();window.__treeStore.reset()});release();await p.waitForTimeout(350);const state=await p.evaluate(()=>({familyId:window.__treeStore.familyId,version:window.__treeStore.version,roots:window.__treeStore.roots,loading:window.__treeStore.loading}));expect(state).toEqual({familyId:null,version:0,roots:[],loading:false})}finally{await c.close()}});
test('invalid and stale route family canonicalize to first available family with one fetch and no loop',async({browser})=>{for(const requested of ['bogus','99999999-9999-4999-8999-999999999999']){const c=await login(browser);try{const p=await c.newPage(),calls=await treeRequests(p);await goTree(p,`/tree?family=${requested}`);await expect(p).toHaveURL(new RegExp(`[?&]family=${A}`));await expect(p.locator('select').first()).toHaveValue(A);await expect.poll(()=>calls.filter(x=>x.endsWith(`/${A}/tree`)).length).toBe(1);await p.waitForTimeout(500);expect(calls.filter(x=>x.endsWith(`/${A}/tree`))).toHaveLength(1);expect(calls.filter(x=>x.endsWith(`/${requested}/tree`))).toHaveLength(0)}finally{await c.close()}}});
